-- =====================================================================
-- SIGMA — struktur indikator: PPI bagian 1 (160 indikator)
--
-- Bagian dari seed_1. Dipecah menjadi tiga berkas agar tiap berkas nyaman
-- ditempel ke SQL Editor tanpa perlu dipotong manual.
-- Jalankan berurutan: 1a, 1b, 1c. Aman dijalankan berulang.
--
-- Catatan teknis: beberapa teks indikator memuat tanda titik koma. Karakter
-- itu ditulis sebagai chr(59) dan disambung dengan tanda pipa ganda, sehingga
-- tidak ada satu pun titik koma di dalam literal string. Berkas tetap utuh
-- walaupun editor memisah perintah berdasarkan titik koma.
-- =====================================================================

insert into public.indicators (id,type,name,code,unit,calc,t2030,strategy_map,outcome,accountability,program,details,toc_foundation,toc_foundation_code,portfolio,portfolio_code,project,project_code,level,result_statement,definition,mov,period) values
('PPI-001','PPI','Human Capital Index for Indonesia (national value)','TPL1.1.1.1.MDTF-OC.1','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','IHCA MDTF INEY World Bank Phase 2','TPL1.1.1','Outcome',null,'The Human Capital Index (HCI) combines indicators ofhealth and education into a measure of the human capitalthat a child born today can expect to obtain by their 18th birthday, on a scale from 0 to 1. Higher values indicate higher expected human capital.',null,null),
('PPI-002','PPI','Prevalence of stunting, height for age (Percentage of children under 5)','TPL1.1.1.1.MDTF-OC.2','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','IHCA MDTF INEY World Bank Phase 2','TPL1.1.1','Outcome',null,'Prevalence of stunting is the percentage of children under age 5 whose height for age is more than two standard deviations below the median for the international reference population ages 0-59 months.',null,null),
('PPI-003','PPI','Number of children under five receiving Pentavalent vaccine/DPT 1 (Number) in priority districts (Number) - from INEY 2','TPL1.1.1.1.MDTF-OC.3','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','IHCA MDTF INEY World Bank Phase 2','TPL1.1.1','Outcome',null,'Number of children aged 0-60 months receiving Pentavalent (DPT – HB – Hib) vaccine in identified under-performing districts. The Pentavalent vaccine, also known as DPT-HB-Hib, is a combination vaccine that protects against multiple diseases, including diphther…',null,null),
('PPI-004','PPI','Percentage of Active beneficiaries covered under JKN','TPL1.1.1.1.MDTF-OC.4','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','IHCA MDTF INEY World Bank Phase 2','TPL1.1.1','Outcome',null,'Active beneficiaries refer to individuals who are currently enrolled and actively participating in the JKN program. This indicator calculates the percentage of these active beneficiaries out of the total population eligible for JKN coverage. Monitoring the per…',null,null),
('PPI-005','PPI','Increased number of private providers that have ever used the relevant TB program information system for TB notification','TPL1.1.1.1.MDTF-OC.5','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','IHCA MDTF INEY World Bank Phase 2','TPL1.1.1','Outcome',null,'Expressed in number of private providers that have ever used (‘ever’ that will be translated as at least 5 - five patients) the relevant TB program information system for TB notification',null,null),
('PPI-006','PPI','Number of Government policies, strategies, and guidelines that reflect MDTF contributions','TPL1.1.1.1.MDTF-O.1','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','IHCA MDTF INEY World Bank Phase 2','TPL1.1.1','Output',null,'This indicator measures the quantity of policies, strategies, and implementation guidelines that have been created by the government using knowledge gained from activities funded by the MDTF (Multi-Donor Trust Fund). These policies, strategies, and guidelines…',null,null),
('PPI-007','PPI','Number of knowledge products produced under the MDTF','TPL1.1.1.1.MDTF-O.2','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','IHCA MDTF INEY World Bank Phase 2','TPL1.1.1','Output',null,'This indicator measures the quantity of knowledge products that have been created based on the insights and knowledge gained from activities funded by the MDTF. These knowledge products can include a variety of formats such as technical guidelines, PowerPoint…',null,null),
('PPI-008','PPI','Number of HDWs trained using modules, curricula, or training of trainers supported by the IHCA MDTF','TPL1.1.1.1.MDTF-O.3','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','IHCA MDTF INEY World Bank Phase 2','TPL1.1.1','Output',null,'This indicator measures the total number (cummulative) of Health and Development Workers (HDW) who have received training using modules, curricula, or training of trainers supported by the MDTF. This indicator measures the transferability of MDTF-generated kno…',null,null),
('PPI-009','PPI','Number of Government budget allocated to programs that utilize MDTF recommendations to advance human capital (in US$ million)','TPL1.1.1.1.MDTF-O.4','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','IHCA MDTF INEY World Bank Phase 2','TPL1.1.1','Output',null,'This indicator measures the amount of financial resources allocated by the government towards programs that implement recommendations provided by the Multi-Donor Trust Fund (MDTF). The indicator reflects the government''s commitment to prioritize and invest in…',null,null),
('PPI-010','PPI','Number of South-South Knowledge Exchange (SSKE) initiatives to promote human capital supported by the MDTF','TPL1.1.1.1.MDTF-O.5','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','IHCA MDTF INEY World Bank Phase 2','TPL1.1.1','Output',null,'This indicator measures the count of initiatives or programs (including workshops, conference attendance, study tours, and speaking engagements) that have been carried out to facilitate the exchange of knowledge and expertise between Indonesia, the Global Sout…',null,null),
('PPI-011','PPI','Percentage of children aged 6–23 months achieving Minimum Dietary Diversity (MDD)','TPL1.1.2.ALPHA-IMP.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','ALPHA','TPL1.1.2','Impact','Improved child diets and feeding practices','The indicator measures whether a child has received foods from a sufficient number of food groups
Numerator : # of Children consumed foods from at least 5 out of 8 specific food groups during the previous day and night
Denominator: Total number of sampled resp…',null,null),
('PPI-012','PPI','Percentage of children aged 6–23 months achieving Minimum Acceptable Diet (MAD)','TPL1.1.2.ALPHA-IMP.2','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','ALPHA','TPL1.1.2','Impact','Improved child diets and feeding practices','The indicator evaluates the combination of the components based on their feeding status.
For a breastfed child: The child meets the MAD indicator if they have achieved both the Minimum Dietary Diversity (MDD) and the Minimum Meal Frequency (MMF).
For a non-bre…',null,null),
('PPI-013','PPI','Percentage of Posyandu deliver quality IYCF and complementary counseling','TPL1.1.2.ALPHA-OC.1','Percent','Annual',0.8,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','ALPHA','TPL1.1.2','Outcome','Strengthened service delivery and growth monitoring','Numerator : # of observed Posyandu that meet quality standard of IYCF and complementary counseling
Denominator : Total number of observed Posyandu',null,null),
('PPI-014','PPI','Number of Puskesmas using standardized supervision and quality improvemnt tools for IYCF and nutrition services','TPL1.1.2.ALPHA-OC.2','Number','Annual',100.0,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','ALPHA','TPL1.1.2','Outcome','Strengthened service delivery and growth monitoring','Numerator : # of intervened Puskemas that use standardized supervision and quality improvement tool
Denominator : Total number of intervened Puskesmas',null,null),
('PPI-015','PPI','Number of Functional mother support groups (Meet standard quality)','TPL1.1.2.ALPHA-IMO.1','Number','Annual',2000.0,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','ALPHA','TPL1.1.2','Intermediate Outcome','Scaled up community engagement and behaviour change','Total number of intervened mother support group functioning according to the standard guideline',null,null),
('PPI-016','PPI','Number of people reached with key nutrition, including stunting and IYCF messages','TPL1.1.2.ALPHA-IMO.2','Number','Annual',50000.0,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','ALPHA','TPL1.1.2','Intermediate Outcome','Scaled up community engagement and behaviour change',null,null,null),
('PPI-017','PPI','Number of national and provincial policies or regulations on child nutrition (IYCF, breastfeeding, and complementary feeding) updated and implemented','TPL1.1.2.ALPHA-O.1','Number','Annual',5.0,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','ALPHA','TPL1.1.2','Output','Strengthened enabling environment and governance',null,null,null),
('PPI-018','PPI','Number of Posyandu in the selected sites receiving at least one supportive supervision visit per year','TPL1.1.2.ALPHA-O.2','Number','Annual',500.0,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','ALPHA','TPL1.1.2','Output','Strengthened enabling environment and governance',null,null,null),
('PPI-019','PPI','Number of villages that has adopted integrated model for acceleration stunting reduction','TPL1.1.3.PASTI-IMP.1','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','PASTI 2.0','TPL1.1.3','Impact','The Partnership to Accelerate Stunting Reduction in Indonesia (PASTI) Project aims to contribute to the acceleration of stunting reduction and improvement of nutrition status in government priority provinces by 2027','Pilot model of villages that implement integrated mechanisms which are mobilized by functioned village level TPPS. This model will include 3 criteria:
1. Functioned TPPS at the village level, indicated by existing workplan, integrated data and regular meetings…','Annual Report
page. 10',null),
('PPI-020','PPI','Proportion of children exclusively breastfed until 6 months of age','TPL1.1.3.PASTI-OC.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','PASTI 2.0','TPL1.1.3','Outcome','Improved access and quality of community-based health and nutrition services for the families at-risk of stunting through the Social Behavior Change Communication (SBCC) interventions and locally contextualized effort from the community','Percent of infants aged less than 6 months were fed exclusively with breast milk in Puskesmas surveilance record. Exclusive breastfeeding (EBF) means the baby has not received any other fluids (not even water) or foods, with the exception of ORS, drops, syrups…','Numerator: Annual Report
page. 19

Denominator: Annual Report
page. 19',null),
('PPI-021','PPI','Percentage of pregnant women with Chronic Energy Deficiency (KEK) who were treated with supplementary nutritious food','TPL1.1.3.PASTI-OC.2','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','PASTI 2.0','TPL1.1.3','Outcome','Improved access and quality of community-based health and nutrition services for the families at-risk of stunting through the Social Behavior Change Communication (SBCC) interventions and locally contextualized effort from the community','Percentage of pregnant women that have MUAC less than 23.5 cm who were treated with supplementary nutritious food
Numerator:
Number of pregnant women that have MUAC less than 23.5 cm graduated from PGD who were treated with supplementary nutritious food
Denomi…','Numerator: Annual Report
page. 38

Denominator: Annual Report
page. 33',null),
('PPI-022','PPI','Percentage of children at risk of stunting with improved nutrition status','TPL1.1.3.PASTI-OC.3','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','PASTI 2.0','TPL1.1.3','Outcome','Improved access and quality of community-based health and nutrition services for the families at-risk of stunting through the Social Behavior Change Communication (SBCC) interventions and locally contextualized effort from the community','Percentage of children that attend series of integrated Pos Gizi Dashat intervention that increase minimum weight standard for Pos Gizi Dashat after 90 days post intervention
Numerator:
Number of children (T1/T2 and/or underweight) that attend series of integr…','Numerator: Annual Report
page. 13

Denominator: Annual Report
page. 13',null),
('PPI-023','PPI','Number of children under two (0-23 months) reached with community-level nutrition interventions','TPL1.1.3.PASTI-OC.4','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','PASTI 2.0','TPL1.1.3','Outcome','Improved access and quality of community-based health and nutrition services for the families at-risk of stunting through the Social Behavior Change Communication (SBCC) interventions and locally contextualized effort from the community','Children under two: 
This indicator captures the children reached from birth to 23 months. Children are counted as reached if they joined the Pos Gizi Dashat.
 
Children reached by community-level nutrition programs should be counted only once per reporting ye…','Annual Report
page. 33',null),
('PPI-024','PPI','Percentage of target beneficiaries who have a good understanding of stunting in priority locations','TPL1.1.3.PASTI-IMO.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','PASTI 2.0','TPL1.1.3','Intermediate Outcome','Improved community’s knowledge and awareness on the importance of quality health and nutrition services for the First 1000 Days families through Social Behavior Change Communication (SBCC) strategies adapted to local context','Percent of parents/caregivers who correctly identify ways of preventing stunting using a tool that delivered after the SBCC activities.

The tool is consisting of 4-point knowledge about stunting as follows:
1. Impairment of brain caused by stunting is irrever…','Numerator: Annual Report
page. 25

Denominator: Annual Report
page. 25',null),
('PPI-025','PPI','Percentage of coverage of families at risk of stunting who get assistance','TPL1.1.3.PASTI-IMO.2','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','PASTI 2.0','TPL1.1.3','Intermediate Outcome','Increased access, coverage, and quality of comprehensive community-based health and nutrition services for the family at-risk of stunting through community empowerment strategies, adapted to local context, and aim to reach the hard-to-reach populatio…','Percentage of families at-risk of stunting that reached through campaign activities and community-based health and nutrition services.

Families who get assistance means those whom ever join in a session of Pos Gizi Dashat without considering whether they comp…','Numerator: Annual Report
page. 19

Denominator: Annual Report
page. 19',null),
('PPI-026','PPI','Percentage of children at risk of stunting that completed community nutrition specific intervention','TPL1.1.3.PASTI-IMO.3','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','PASTI 2.0','TPL1.1.3','Intermediate Outcome','Increased access, coverage, and quality of comprehensive community-based health and nutrition services for the family at-risk of stunting through community empowerment strategies, adapted to local context, and aim to reach the hard-to-reach populatio…','Percentage of children at risk of stunting that completed community nutrition specific intervention, namely Pos Gizi Dashat.

Children at risk of stunting are those who classified as underweight, T1 or T2 that were referred to Pos Gizi Dashat by TPK. T1 means…',null,null),
('PPI-027','PPI','Number of routine meetings of TPPS using village budget','TPL1.1.3.PASTI-O.1','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','PASTI 2.0','TPL1.1.3','Output','Ensured referral of families at-risk of stunting to various nutrition-specific and nutrition-sensitive interventions through the assistance of TPK and/or other actors in the community','Total of rountine meeting means TPPPS conducting meeting using village budget','Annual Report
page. 69',null),
('PPI-028','PPI','Number of villages that have maps of health and social referrals for families at-risk of stunting','TPL1.1.3.PASTI-O.2','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','PASTI 2.0','TPL1.1.3','Output','Ensured referral of families at-risk of stunting to various nutrition-specific and nutrition-sensitive interventions through the assistance of TPK and/or other actors in the community','Total number of villages that have maps/ flow of health referral and social referral for families at risk of stunting. This flow should consist of referral flow from village up to district level and socialized to communities.','Annual Report
page. 47',null),
('PPI-029','PPI','Number of youth (15-19) reached with PASTI assistance','TPL1.1.3.PASTI-O.3','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','PASTI 2.0','TPL1.1.3','Output','Strengthened roles and skills of adolescents (boys and girls) in reproductive health campaigns and stunting prevention Days families through Social Behavior Change Communication (SBCC) strategies adapted to local context','Total number of youth 15-19 yo who received knowledge and awareness about reproductive health and stunting prevention through Social Behavior Change Communication (SBCC) strategies that were delivered by trained peer educators','Annual Report
page. 56',null),
('PPI-030','PPI','Number of publication of stunting data at village level','TPL1.1.3.PASTI-O.4','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','PASTI 2.0','TPL1.1.3','Output','Develop/improved integrated monitoring evaluation system and data management as a result of coordination and collaboration across key sectors in accelerating stunting reduction in the Region to the Village','Publication refers to a dashboard of stunting data at village level that is published at least 6-monthly as a result of integrated monitoring and evaluation mechanisms developed. This publication also needs to be reported to SIGA (Sistem Informasi Keluarga) of…','Annual Report
page. 76',null),
('PPI-031','PPI','Percentage of Stunting reduction','TPL1.1.4.SR-IMP.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Impact','The stunting rate at national and supported districts is reduced','National Survey (RISKESDAS/SKI) – Suggest to delete national prevalence stunting','National Survey (RISKESDAS/SKI)',null),
('PPI-032','PPI','Percentage of districts with stunting rate below SDG target (18%)','TPL1.1.4.SR-IMP.2','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Impact','The stunting rate at national and supported districts is reduced','National Survey (RISKESDAS/SKI)','National Survey (RISKESDAS/SKI)',null),
('PPI-033','PPI','Percentage of iron supplement consumption among pregnant mother (average partner district)','TPL1.1.4.SR-OC.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Outcome','Stunting determinants improved','Sampled pregnant mother reported IFA consumption according recommendation / Total sampled pregnant mother','Impact measurement result (Baseline-Endline)',null),
('PPI-034','PPI','Percentage of mother receiving antenatal care (average partner district)','TPL1.1.4.SR-OC.2','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Outcome','Stunting determinants improved','Sampled mother reported >= 6 visit health facility including Posyandu to check their pregnancy/ Total sampled mother','Impact measurement result (Baseline-Endline)',null),
('PPI-035','PPI','Rate of exclusive breastfeeding (average partner district)','TPL1.1.4.SR-OC.3','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Outcome','Stunting determinants improved','Sampled mother with children aged 24 month old reported exclusive breastfeeding for children aged under 6 months/Total sampled mother with child aged 24 month old','Impact measurement result (Baseline-Endline)',null),
('PPI-036','PPI','Rate of proper infant and child feeding (average partner district)','TPL1.1.4.SR-OC.4','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Outcome','Stunting determinants improved','Sampled mother with children aged 24 month old with timely complementary feeding practice/Total sampled mother with child aged 24 month old','Impact measurement result (Baseline-Endline)',null),
('PPI-037','PPI','Percentage of children under 5 y.o. monitored regularly','TPL1.1.4.SR-OC.5','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Outcome','Stunting determinants improved','Sampled mother with children aged 24 month old reported at least 8 times Posyandu visit in a year/Total sampled mother with child aged 24 month old','Impact measurement result (Baseline-Endline)',null),
('PPI-038','PPI','Percentage of at risk children & family received intervention','TPL1.1.4.SR-OC.6','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Outcome','Stunting at-risk children & family receive intervention','Extracted from POPS data
Total number of children under two years old and pregnant mother at risk (malnutrion) received intervention / total number of children under two years old at risk (children with undernutrition including weight flattering, and pregnant…','Impact measurement result (Baseline-Endline)',null),
('PPI-039','PPI','Percentage of targeted group members with appropriate stunting knowledge','TPL1.1.4.SR-IMO.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Intermediate Outcome','Knowledge around stunting are improved','Sampled mother with under 2 years old and pregnant mother with basic knowledge of stunting /Total sampled mother with under 2 years old and pregnant mother','Impact measurement result (Baseline-Endline)',null),
('PPI-040','PPI','Percentage of family reported reached by stunting campaign activities in the last 6 months (community leader, campaign, social media, etc)','TPL1.1.4.SR-IMO.2','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Intermediate Outcome','Family received accurate information about stunting','BCC activities : 
Campaign, Interpersonal Counseling, Media social
Sampled mother with under 2 years old and pregnant mother reported received stunting information/Total sampled mother with under 2 years old and pregnant mother','Impact measurement result (Baseline-Endline)',null),
('PPI-041','PPI','Percentage of trained community leaders conducted stunting campaign in the last 6 month','TPL1.1.4.SR-O.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Improved capacity of community leaders to increase awareness of community members on key health & nutrition practices','Total trained (In BCC) community leaders conducted BCC in the last 6 month/Total trained (in BCC) community leaders','Activitiy report',null),
('PPI-042','PPI','Number of community leaders trained in BCC','TPL1.1.4.SR-O.2','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Improved capacity of community leaders to increase awareness of community members on key health & nutrition practices','Total trained (In BCC) community leaders conducted BCC in the last 6 month/Total trained (in BCC) community leaders','Activitiy report',null),
('PPI-043','PPI','Percentage of district with BCC activities are included in district planning*','TPL1.1.4.SR-O.3','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of district-level government in planning and budgeting for stunting-related actions','BCC activities : 
Campaign, Interpersonal Counseling, Media socialCheck Aksi 2 in convergent action','District planning doc /E-BANGDA',null),
('PPI-044','PPI','Percentage of village locus stunting received socialization of stunting program or local regulation/policy','TPL1.1.4.SR-O.4','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of district-level government in planning and budgeting for stunting-related actions','Check dashboard convergent action','District govt report (E-BANGDA)',null),
('PPI-045','PPI','Percentage of village locus stunting received mentoring in the last 6 months from district government','TPL1.1.4.SR-O.5','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of district-level government in planning and budgeting for stunting-related actions','Mentoring activities will refer to agreed mechanism/regulation/guidance (ie : cascade mentoring district-sub district-village)','Activity report',null),
('PPI-046','PPI','Percentage of district with increased budget allocation/ budget absorption for sensitive and specific intervention (latest financial year after intervention started)','TPL1.1.4.SR-O.6','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of district-level government in planning and budgeting for stunting-related actions','Number of district reported increase budget allocation / budget absoption for sensitive and specific intervention/Total intervened districts
Check dashboard convergent action','District govt report (E-BANGDA)',null),
('PPI-047','PPI','Percentage of district implemented pra-rembuk stunting','TPL1.1.4.SR-O.7','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of district-level government in planning and budgeting for stunting-related actions','Number of district reported implementation of pra-rembuk stunting/Total intervened districts','Activity report',null),
('PPI-048','PPI','Percentage of pregnant mother received iron tablet in intervened districts','TPL1.1.4.SR-O.8','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased coverage of nutrition-specific and nutrition-sensitive services to family with U5 children/pregnant mothers (O)','Extracted from E-BANGDA. 
Cumulative percentage of pregnant mother received Iron tablet across districts under intervened areas/Total number of districts under intervened areas','Govt Survey/Report / E-BANGDA',null),
('PPI-049','PPI','Percentage of Posyandu attendance coverage for children U5 within POPS working areas','TPL1.1.4.SR-O.9','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased coverage of nutrition-specific and nutrition-sensitive services to family with U5 children/pregnant mothers (O)','Extracted from E-PPBGM recorded in POPS
Cumulative of average percentage of attendance coverage of children under five years old for each month from villages within POPS working areas / Total number of months under reporting areas start from effective POPS','Digital platform (POPS)',null),
('PPI-050','PPI','Percentage of of district with annual update on key stunting data used in district convergent planning','TPL1.1.4.SR-O.10','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of district-level government in monitoring and use of data for decision making','Extracted from E-BANGDA','E-BANGDA',null),
('PPI-051','PPI','Number of district with mentoring/monitoring for stunting intervention (BCC, Convergent) mechanism','TPL1.1.4.SR-O.11','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of district-level government in monitoring and use of data for decision making','District with established mechanism fo monitor/mentoring implementation of stunting program (including BCC). Report should explain how frequent monitoring/mentoring will be conducted, mechanism (coordination meeting and or visit), field visit plan (if any)','Activity report',null),
('PPI-052','PPI','Number of district official/representative participate in stunting workshop','TPL1.1.4.SR-O.12','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of district-level government in monitoring and use of data for decision making','Total number of district official participated in stunting workshop facilitated by program to strengthen their understanding related to stunting issues (Nasional and or sub national of : new regulation, STRANAS, guidance, etc)','Activity report',null),
('PPI-053','PPI','Number of village with POPS established','TPL1.1.4.SR-O.13','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of village-level government in data management and use for decision making','POPS established : (Web app ready to use, Required data from E-PPBGM, TPK Intervention imported to POPS)','Activity report',null),
('PPI-054','PPI','Number of village with data updated and consolidated at regular basis','TPL1.1.4.SR-O.14','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of village-level government in data management and use for decision making','Monthly update of E-PPBGM, TPK, and Intervention','Activity report',null),
('PPI-055','PPI','Number of villages analyze data & use for decision making to address stunting issues','TPL1.1.4.SR-O.15','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of village-level government in data management and use for decision making','Data and analysis from POPS presented and used in regulat TP3S meeting','Activity report',null),
('PPI-056','PPI','Number of village representative trained','TPL1.1.4.SR-O.16','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of village-level government in data management and use for decision making','Total number of village representative trained in POPS','Activity report',null),
('PPI-057','PPI','Number of village leader trained in data driven decision making','TPL1.1.4.SR-O.17','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of village-level government in data management and use for decision making','Village head/TP3S head or other village representative introduced on key POPS feature for decision making for stunting program (identified malnutrition children, planning for intervention)','Activity report',null),
('PPI-058','PPI','Number of village with platform subscription is budgeted by village/district government','TPL1.1.4.SR-O.18','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Maternal and Child Health & Nutrition (MCHN)','TPL1.1','District Stunting Reduction (SR)','TPL1.1.4','Output','Increased capacity of village-level government in data management and use for decision making','Platform subscription to host POPS App in 2027','Activity report',null),
('PPI-059','PPI','Percentage of children 0–3 with development scores equal to or above the population reference','TPL1.2.1.RAS-IMP.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Impact','Optimal development of children aged 0–3 years in intervention areas','Numerator: # of children 0–3 with development score ≥ population reference
Denominator: total # of children 0–3 assessed in intervention areas','CREDI baseline–endline',null),
('PPI-060','PPI','Percentarge of caregivers with caregiving knowledge score ≥ 70','TPL1.2.1.RAS-OC.1','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Increased caregiver (primary caregiver) knowledge and positive caregiving practices','Numerator: Caregivers attending age‑specific thematic sessions who achieve ≥ 70 on the knowledge post‑test 
Denominator: total participating caregivers in the period','Knowledge post‑test results',null),
('PPI-061','PPI','Average score of positive caregiving practices','TPL1.2.1.RAS-OC.2','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Increased caregiver (primary caregiver) knowledge and positive caregiving practices','Composite practice score (HOME instrument)','Baseline/Endline - HOME',null),
('PPI-062','PPI','Score of Maternal Confidence (Postponed)','TPL1.2.1.RAS-OC.3','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Increased caregiver (primary caregiver) knowledge and positive caregiving practices','TBD'||chr(59)||' explore MCQ or Toddler Care Questionnaire with psychology department','Baseline–Endline (when tool finalized)',null),
('PPI-063','PPI','Scale of Caregiver Wellness (Postponed)','TPL1.2.1.RAS-OC.4','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Increased caregiver (primary caregiver) knowledge and positive caregiving practices','TBD'||chr(59)||' rapid questionnaire aligned to program focus and Indonesian context','Baseline–Endline (when tool finalized)',null),
('PPI-064','PPI','Number of children 0–3 registered in RAS (Cumulative)','TPL1.2.1.RAS-OC.5','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Improved access to and quality of holistic, integrated services for children 0–3','Number of registered children in RAS database','Beneficiary data',null),
('PPI-065','PPI','Number of children 0–3 actively participating in RAS (Annual)','TPL1.2.1.RAS-OC.6','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Improved access to and quality of holistic, integrated services for children 0–4','Children in database with Active status in a given year','Beneficiary data',null),
('PPI-066','PPI','Percentage of RAS with average service quality score ≥ 75','TPL1.2.1.RAS-OC.7','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Improved access to and quality of holistic, integrated services for children 0–5','# of RAS with avg. observation score ≥ 75 ÷ total RAS observed','Semester service‑quality observations','Semester'),
('PPI-067','PPI','Percentage of children with improved developmental status','TPL1.2.1.RAS-OC.8','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Improved access to and quality of holistic, integrated services for children 0–6','# of children with improved ASQ developmental status ÷ total assessed in monitoring areas','ASQ measurements (semesterly)','Semester'),
('PPI-068','PPI','Percentage of facilitators with caregiving knowledge score ≥ 80','TPL1.2.1.RAS-OC.9','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Improved access to and quality of holistic, integrated services for children 0–7','Facilitators completing age‑specific thematic sessions and scoring ≥ 80 ÷ total facilitators in the period','Post‑test reports',null),
('PPI-069','PPI','Percentage of facilitators meeting minimum service delivery targets','TPL1.2.1.RAS-OC.10','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Improved access to and quality of holistic, integrated services for children 0–8','Community cadre: ≥ 3 services/month'||chr(59)||' Individual stimulation facilitator: ≥ 6 topics/child/month','Monitoring system',null),
('PPI-070','PPI','Number of villages with policies supporting early childhood services','TPL1.2.1.RAS-OC.11','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Strengthened enabling ecosystem for early childhood development','May include regulations'||chr(59)||' operational support'||chr(59)||' RAS budget in planning documents','Letter of Commitment for support RAS',null),
('PPI-071','PPI','Total funding committed to RAS','TPL1.2.1.RAS-OC.12','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Strengthened enabling ecosystem for early childhood development','Aggregate amount allocated to RAS in village/district plans','Village development plans',null),
('PPI-072','PPI','Number of villages providing funding for RAS','TPL1.2.1.RAS-OC.13','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Outcome','Strengthened enabling ecosystem for early childhood development','Number of villages allocating funds for RAS','Village/district documents',null),
('PPI-073','PPI','Percentage of child–caregiver dyads meeting minimum interaction targets (Target: 70Percentage)','TPL1.2.1.RAS-O.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Output','Parent/caregiver participation in RAS','Minimum interactions: 0–6 months: 3'||chr(59)||' 
Denominator: 6–36 months: 6 of 7 visit','RAS 0–3 monitoring dashboard',null),
('PPI-074','PPI','Number of government/stakeholders engaged in early childhood policy socialization','TPL1.2.1.RAS-O.2','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Output','Participation of village officials and district government in caregiving for 0–3','Includes representatives of village/sub‑district/district offices and community leaders','Activity report',null),
('PPI-075','PPI','Number of coordination meetings at district/sub‑district/village levels on caregiving and early stimulation','TPL1.2.1.RAS-O.3','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Rumah Anak Sigap (RAS)','TPL1.2.1','Output','Participation of village officials and district government in caregiving for 0–4','Number of meetings held','Activity report',null),
('PPI-076','PPI','Pecentage point of increase in teaching practices in the domains Play-based mathematics','TPL1.2.2.SAS-OC.1','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Sekolah Anak Sigap (SAS)','TPL1.2.2','Outcome','Improved teaching practice in play-based learning and mathematics in classroom','Numerator: # of observed teacher who applied play based mathematic during class observation
Denominator: Total number teacher''s observation','Observation checklist before-after intervention',null),
('PPI-077','PPI','Percentage point of increase supportive playful math activities with children at home','TPL1.2.2.SAS-OC.2','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Sekolah Anak Sigap (SAS)','TPL1.2.2','Outcome','Increased parent engagement with children in conducting learning activities at home, in terms of frequency and variety','Numerator: # of caregiver reported math activities(3 type, more than one time in a week) at home with children
Denominator : Total number caregiver involved in survey','Online survey before-after intervention',null),
('PPI-078','PPI','Percentage of teachers meeting minimum knowledge score (70) post training on play-based mathematics','TPL1.2.2.SAS-IMO.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Sekolah Anak Sigap (SAS)','TPL1.2.2','Intermediate Outcome','Improved teacher knowledge and skill in play-based learning and Mathematics','Numerator: # of trained teacher with post test score >= 70
Denominator: Total number of trained teacher involved in post-test','Post test at each training',null),
('PPI-079','PPI','Percentage of parents meeting minimum knowledge score (70) post training on play-based mathematics activities','TPL1.2.2.SAS-IMO.2','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Sekolah Anak Sigap (SAS)','TPL1.2.2','Intermediate Outcome','Improved parents knowledge and skill in play-based learning and Mathematics','Numerator: # of parent with post test knowledge score >=70
Denominator: # Total parents involved in intervention who participate in post-test','Post test at each training',null),
('PPI-080','PPI','Number of teachers participated in training (segregated by modules & schools)','TPL1.2.2.SAS-O.1','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Sekolah Anak Sigap (SAS)','TPL1.2.2','Output','Teachers are trained on themes play-based learning and Mathematics',null,'Training attendance records',null),
('PPI-081','PPI','Number of parents participated in duta parenting session at school','TPL1.2.2.SAS-O.2','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Sekolah Anak Sigap (SAS)','TPL1.2.2','Output','Parents are trained on how to support learning and maths at home',null,'Training attendance records',null),
('PPI-082','PPI','Number of parents reached through campaign/ Whatsapp','TPL1.2.2.SAS-O.3','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Sekolah Anak Sigap (SAS)','TPL1.2.2','Output','Parent received information (nudged) via Whatsapp','# of registed phone number in whatsapp group where information of playbased math are shared','Registered WAG phone number',null),
('PPI-083','PPI','Percentage of Children aged 0-6 developmentally on-track','TPL1.2.3.SPRING-IMP.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Early Stimulation in Primary Health Service Integration (SPRING)','TPL1.2.3','Impact','Improved Children Development Outcome','Numerator: # of children 0–3 with development score ≥ population reference
Denominator: total # of children 0–3 assessed in intervention areas','Children aged 0-6 year old survey',null),
('PPI-084','PPI','Average score of caregiver’s quality stimulation practices at home','TPL1.2.3.SPRING-OC.1','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Early Stimulation in Primary Health Service Integration (SPRING)','TPL1.2.3','Outcome','Improved quality stimulation practices by caregiver','Numerator: # of children 0–3 with development score ≥ population reference
Denominator: total # of children 0–3 assessed in intervention areas','Caregiver with children aged 0-6 year old survey',null),
('PPI-085','PPI','Average score of caregiver’s quality stimulation practices at home','TPL1.2.3.SPRING-OC.2','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Early Stimulation in Primary Health Service Integration (SPRING)','TPL1.2.3','Outcome','Increased Stimulation Awareness & Motivation of Caregiver','Average score (1-100) of caregiver''s practices of recomended caring practices achieved by sampled of caregiver','Pustu/Puskesmas Record - data Monthly
Q1 Link: https://docs.google.com/spreadsheets/d/19RzDBtiJ0Y2HACkrhHPoOanp4sit_4TtmDPqRiFRLaM/edit?gid=…',null),
('PPI-086','PPI','Percentage of Caregiver participate in stimulation education session in Posyandu','TPL1.2.3.SPRING-IMO.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Early Stimulation in Primary Health Service Integration (SPRING)','TPL1.2.3','Intermediate Outcome','Improved Access to Quality Education Stimulation Service','Numerator: # of registered caregiver with under five years old children attend education session in Posyandu
Denominator: Total registered caregiver with under five years old children','Attendance record - data Monthly
Q1 Link: https://docs.google.com/spreadsheets/d/177S8_cGoGi0vHW4rlFVWbAnYEgFliunLo3PO_LxC0J8/edit?usp=shari…',null),
('PPI-087','PPI','Number of policy or guideline for stimulation service implementation','TPL1.2.3.SPRING-IMO.2','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Early Stimulation in Primary Health Service Integration (SPRING)','TPL1.2.3','Intermediate Outcome','Improved policy to support stimulation services implementation','policy or guideline document to ensure quality stimulation service implementation developed, and shared with govertment','Policy document/guideline
Folder: 05 TRACKER DUKUNGAN KEBIJAKAN
https://drive.google.com/drive/folders/1gOsuSiLaHpCI-1WkwkhSdvrPfQoZ56Hc?usp…',null),
('PPI-088','PPI','Percentage of Posyandu meet quality education session','TPL1.2.3.SPRING-O.1','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Early Stimulation in Primary Health Service Integration (SPRING)','TPL1.2.3','Output','Improved Access to Quality Stimulation Services','Quality education session measure use quality check list refer to agreed SOP
Numerator: # of Posyandu with observation education session score >= 75
Denominator: Total intervened Posyandu','Observation report 
Link: https://docs.google.com/spreadsheets/d/1Tegw-lNydXLCEG9Jd6K9VvjcZNJfWsIN/edit?gid=1793448115#gid=1793448115

Q2 Li…',null),
('PPI-089','PPI','Percentage of Facilitator meet quality stimulation service','TPL1.2.3.SPRING-O.2','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Early Stimulation in Primary Health Service Integration (SPRING)','TPL1.2.3','Output','Improved Access to Quality Education Stimulation Servic','Quality stimulation service measure use quality check list refer to agreed SOP
Numerator: # of observed facilitator with stimulation service score >= 75
Denominator: Total observed facilitator','Observation report 
Q1 Link: https://docs.google.com/spreadsheets/d/1vCOY2_bnXYPG18y4uJRzQ1w1OuUX-t2v/edit?gid=2068714812#gid=2068714812

Q2…',null),
('PPI-090','PPI','Percentage of Cadre/Health staff/Communities trained in education session and/or stimulation services','TPL1.2.3.SPRING-O.3','Percent','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Early Stimulation in Primary Health Service Integration (SPRING)','TPL1.2.3','Output','Improved Capacity of Cadre, Health staff and Communities',null,'Program report
Data Peserta Pelatihan: https://docs.google.com/spreadsheets/d/17V0kF3aT7VqcCEeTNOwUU2hgVdjgHCiY/edit?usp=sharing&ouid=108379…',null),
('PPI-091','PPI','Number of SBCC training module/Stimulation services developed','TPL1.2.3.SPRING-O.4','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Early Stimulation in Primary Health Service Integration (SPRING)','TPL1.2.3','Output','Improved Access to Stimulation information',null,'Program report
Folder: https://bit.ly/SPRING-PROJECT',null),
('PPI-092','PPI','Number of Coordination meeting/Join monitoring with government on stimulation for children aged 0-6 yo','TPL1.2.3.SPRING-O.5','Number','Annual',null,null,null,null,null,null,'Children receive proper care and developmentally on track','TFL1','Early Childhood Education and Development (ECED)','TPL1.2','Early Stimulation in Primary Health Service Integration (SPRING)','TPL1.2.3','Output','Improved awareness of government on stimulation and services',null,'Program report
Q1 Link: https://drive.google.com/drive/folders/1RCYegqaZAH-qRu26EzyUN6BEDwozKUVf?usp=drive_link
Q2 Link: https://drive.googl…',null),
('PPI-093','PPI','Frequency of teachers apply contextualised learning in the classroom','TPL2.1.2.PCK-IMO.1','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Teachers apply contextualized learning in the classroom [BEHAVIOUR]','The number of observed mathematics lessons in which the teacher integrates real-life examples or contexts aligned with the guidebook or contextualised learning principles.','Evaluation report',null),
('PPI-094','PPI','Frequency of teachers creating new examples when teaching maths','TPL2.1.2.PCK-IMO.2','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Teachers apply contextualized learning in the classroom [BEHAVIOUR]','The number of mathematics lessons where the teacher independently generates original real-life examples (not directly copied from the guidebook).','Evaluation report',null),
('PPI-095','PPI','Percentage of teachers who find contextualised learning as a more effective approach','TPL2.1.2.PCK-IMO.3','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Teachers apply contextualized learning in the classroom [BEHAVIOUR]','The proportion of teachers who report that contextualised learning is more effective than traditional teaching methods for improving student understanding.','Evaluation report',null),
('PPI-096','PPI','Percentage of teachers who can recognize and use real-life examples to teach mathematics','TPL2.1.2.PCK-IMO.4','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Teachers are able to plan appropriate lesson plans for maths [SKILL]','The proportion of teachers who correctly identify appropriate real-life contexts for given mathematical concepts in an assessment task.','Evaluation report',null),
('PPI-097','PPI','Percentage of teachers who can select appropriate media or tools to support mathematics teaching','TPL2.1.2.PCK-IMO.5','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Teachers are able to plan appropriate lesson plans for maths [SKILL]','The proportion of teachers who can correctly select suitable learning media aligned with lesson objectives.','Evaluation report',null),
('PPI-098','PPI','Percentage of teachers who can design relevant and level-appropriate math problems for instruction and assessment','TPL2.1.2.PCK-IMO.6','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Teachers are able to plan appropriate lesson plans for maths [SKILL]','The proportion of teachers who can construct grade-appropriate contextual math problems aligned with curriculum standards (Grades 1–3).','Evaluation report',null),
('PPI-099','PPI','Percentage teachers’ proficiency in the number sense','TPL2.1.2.PCK-IMO.7','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Improve teacher'' content knowledge (CK) and pedagogical content knowledge (PCK) [KNOWLEDGE]','The proportion of teachers scoring above the minimum competency threshold in number sense assessment covering cardinality, number symbols, place value, and whole numbers.','Evaluation report',null),
('PPI-100','PPI','Percentage teachers’ proficiency in mathematical operations','TPL2.1.2.PCK-IMO.8','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Improve teacher'' content knowledge (CK) and pedagogical content knowledge (PCK) [KNOWLEDGE]','The proportion of teachers achieving minimum competency in operations','Evaluation report',null),
('PPI-101','PPI','Percentage teachers’ understanding of children’s numeracy skills','TPL2.1.2.PCK-IMO.9','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Improve teacher'' content knowledge (CK) and pedagogical content knowledge (PCK) [KNOWLEDGE]','The proportion of teachers correctly identifying developmental progression in foundational numeracy (number concept, operations, word problems, geometry).','Evaluation report',null),
('PPI-102','PPI','Percentage teachers ability to anticipate common misconceptions and addresses them','TPL2.1.2.PCK-IMO.10','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Improve teacher'' content knowledge (CK) and pedagogical content knowledge (PCK) [KNOWLEDGE]','The proportion of teachers who correctly identify common student misconceptions and select appropriate remediation strategies.','Evaluation report',null),
('PPI-103','PPI','Number of teachers trained (headcount)','TPL2.1.2.PCK-O.1','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Teachers attend and are engaged with all training sessions','Total number of unique teachers who attended at least one full training day during the official Teacher Training (Roll-Out) period.','Participant attendance form',null),
('PPI-104','PPI','Average teacher attendance rate in Teacher Training (Roll-Out) sessions (Percentage)','TPL2.1.2.PCK-O.2','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Teachers attend and are engaged with all training sessions','Average proportion of total training sessions attended by each registered teacher.','Participant attendance form',null),
('PPI-105','PPI','Average point increase in teachers’ knowledge assessment scores','TPL2.1.2.PCK-O.3','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Teachers attend and are engaged with all training sessions','Mean difference between post-test and pre-test knowledge scores (raw points).','Pre and Post Test Result',null),
('PPI-106','PPI','Average percentage increase in teachers’ knowledge assessment scores (Percentage)','TPL2.1.2.PCK-O.4','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Teachers attend and are engaged with all training sessions','Mean relative improvement in knowledge score compared to pretest.','Pre and Post Test Result',null),
('PPI-107','PPI','Number of teachers who received mentoring sessions (headcount)','TPL2.1.2.PCK-O.5','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Teachers receive continuous guide on how to prepare appropriate lesson plans','Total number of unique teachers who participated in at least one structured mentoring session during the reporting period.','Participant attendance form',null),
('PPI-108','PPI','Average teacher attendance rate in Mentoring sessions (Percentage)','TPL2.1.2.PCK-O.6','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Teachers receive continuous guide on how to prepare appropriate lesson plans','Average proportion of mentoring sessions attended by each teacher out of the total mentoring sessions offered to them.','Participant attendance form',null),
('PPI-109','PPI','Number of facilitators trained (headcount)','TPL2.1.2.PCK-O.7','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Deliver training for teachers to strengthen their mathematics pedagogical content knowledge.','Total number of unique facilitators who completed the full Training of Trainers (ToT) program.','Participant attendance form',null),
('PPI-110','PPI','Average facilitator attendance rate in Training of Trainers (ToT) sessions (Percentage)','TPL2.1.2.PCK-O.8','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Deliver training for teachers to strengthen their mathematics pedagogical content knowledge.','Average proportion of ToT sessions attended by registered facilitators.','Participant attendance form',null),
('PPI-111','PPI','Average point increase in facilitators’ knowledge assessment scores','TPL2.1.2.PCK-O.9','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Deliver training for teachers to strengthen their mathematics pedagogical content knowledge.','Mean difference between facilitator post-test and pre-test scores (raw points).','Pre and Post Test Result',null),
('PPI-112','PPI','Average percentage increase in facilitators’ knowledge assessment scores (Percentage)','TPL2.1.2.PCK-O.10','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Deliver training for teachers to strengthen their mathematics pedagogical content knowledge.','Mean relative percentage increase in facilitator knowledge from baseline.','Pre and Post Test Result',null),
('PPI-113','PPI','Number of facilitators attending mentoring preparation sessions (headcount)','TPL2.1.2.PCK-O.11','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Provide ongoing mentoring sessions to support teachers’ continuous improvement in classroom practice.','Total number of unique facilitators who attended at least one formal mentoring preparation session before conducting mentoring.','Participant attendance form',null),
('PPI-114','PPI','Average facilitator attendance rate in mentoring preparation sessions (Percentage)','TPL2.1.2.PCK-O.12','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Provide ongoing mentoring sessions to support teachers’ continuous improvement in classroom practice.','Average proportion of mentoring preparation sessions attended by facilitators out of total preparation sessions offered.','Participant attendance form',null),
('PPI-115','PPI','Number of facilitators conducting mentoring sessions (headcount)','TPL2.1.2.PCK-O.13','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Provide ongoing mentoring sessions to support teachers’ continuous improvement in classroom practice.','Total number of facilitators who independently conducted at least one mentoring session with teachers during the reporting period.','Participant attendance form',null),
('PPI-116','PPI','Average of minutes parents spend on helping their children with homework','TPL2.1.2.PCK-IMO.11','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Parents are more involved in supporting children’s education [BEHAVIOUR]','Average total minutes per week parents actively assist child in completing homework','Evaluation report',null),
('PPI-117','PPI','Average of minutes parents spend on accompanying their children when studying','TPL2.1.2.PCK-IMO.12','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Parents are more involved in supporting children’s education [BEHAVIOUR]','Average minutes per week parents supervise study time','Evaluation report',null),
('PPI-118','PPI','Average of minutes parents spend on reading story books together with children','TPL2.1.2.PCK-IMO.13','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Parents are more involved in supporting children’s education [BEHAVIOUR]','Average minutes per week spent reading storybooks together','Evaluation report',null),
('PPI-119','PPI','Average of minutes parents spend on doing educational activities','TPL2.1.2.PCK-IMO.14','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Parents are more involved in supporting children’s education [BEHAVIOUR]','Average minutes per week spent conducting structured learning activities (including HBNA)','Evaluation report',null),
('PPI-120','PPI','Frequency of parents taking the initiative to ask their children to learn at home under their supervision','TPL2.1.2.PCK-IMO.15','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Parents are more involved in supporting children’s education [BEHAVIOUR]','Number of times per week parent initiates learning session without being prompted by school','Evaluation report',null),
('PPI-121','PPI','Shift in parents’ attitude of their roles in supporting their children education','TPL2.1.2.PCK-IMO.16','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Improve parents’ belief and confidence in helping their children learn [BELIEF]','Change in agreement with statement: “It is my responsibility to actively support my child’s learning”','Evaluation report',null),
('PPI-122','PPI','Shift in parents’ perceived norms of their roles in supporting their children education','TPL2.1.2.PCK-IMO.17','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Improve parents’ belief and confidence in helping their children learn [BELIEF]','Change in agreement with statement: “Most parents like me actively support their child’s learning at home”','Evaluation report',null),
('PPI-123','PPI','Shift in parents’ perceived behavioural control in supporting their children education','TPL2.1.2.PCK-IMO.18','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Improve parents’ belief and confidence in helping their children learn [BELIEF]','Change in agreement with statement: “I am capable of helping my child understand maths”','Evaluation report',null),
('PPI-124','PPI','Shift in parents’ behavioural intention to support their children learning','TPL2.1.2.PCK-IMO.19','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Improve parents’ belief and confidence in helping their children learn [BELIEF]','Change in agreement with statement: “I intend to regularly support my child’s numeracy learning”','Evaluation report',null),
('PPI-125','PPI','Improve in parents'' attitude towards maths','TPL2.1.2.PCK-IMO.20','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Improve parents’ belief and confidence in helping their children learn [BELIEF]','Change in agreement with positive statements about maths usefulness and enjoyment','Evaluation report',null),
('PPI-126','PPI','Percentage of parents who are not anxious when doing maths problems','TPL2.1.2.PCK-IMO.21','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Improve parents’ belief and confidence in helping their children learn [BELIEF]','Percentage of parents scoring below threshold on validated math anxiety scale','Evaluation report',null),
('PPI-127','PPI','Percentage of parents who put importance on their involvement on their children education','TPL2.1.2.PCK-IMO.22','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Intermediate Outcome','Improve parents’ awareness on the importance of their involvement [AWARENESS]','% of parents rating parental involvement as “very important”','Evaluation report',null),
('PPI-128','PPI','Number of briefing sessions conducted for PICs (Person-in-Charge)','TPL2.1.2.PCK-O.1','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Information Session on the Importance of Parental Engagement in Supporting Children’s Education','Count number of session','Attendance',null),
('PPI-129','PPI','Number of parent socialisation sessions conducted','TPL2.1.2.PCK-O.2','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Information Session on the Importance of Parental Engagement in Supporting Children’s Education','Count number of session','Attendance',null),
('PPI-130','PPI','Number of onboarding Message I successfully delivered','TPL2.1.2.PCK-O.3','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Weekly Instructions to Parents on How to Conduct Numeracy Learning Activities at Home','Count number of onboarding I message delivered
Target: # Message sent
Actual: # Message successfully delivered','Pingtar Chatbot',null),
('PPI-131','PPI','Number of onboarding Message II successfully delivered','TPL2.1.2.PCK-O.4','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Weekly Instructions to Parents on How to Conduct Numeracy Learning Activities at Home','Count number of onboarding II message delivered
Target: # Message sent
Actual: # Message sent - # Message failed to send','Pingtar Chatbot',null),
('PPI-132','PPI','Number of HBNA content sent','TPL2.1.2.PCK-O.5','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Weekly Instructions to Parents on How to Conduct Numeracy Learning Activities at Home','Count number of HBNA content sent
In Total HBNA
Target: # Content sent
Actual: # Content sent - # Content failed to send','Pingtar Chatbot',null),
('PPI-133','PPI','Number of PICs who attended on the PIC briefing','TPL2.1.2.PCK-O.6','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Parents’ Attendance and Participation in the Sessions','Count number of PIC','Attendance',null),
('PPI-134','PPI','Number of parents who attended on the socialization','TPL2.1.2.PCK-O.7','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Parents’ Attendance and Participation in the Sessions','Count number of parents who attended the socialization session','Attendance',null),
('PPI-135','PPI','Number of parents who received Onboarding Message I','TPL2.1.2.PCK-O.8','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Parents Receiving Messages and Conducting Structured Activities at Home','Count number of parents received 1st onboarding
Target: # Message sent
Actual: # Message opened','Pingtar Chatbot',null),
('PPI-136','PPI','Number of parents who received Onboarding Message II','TPL2.1.2.PCK-O.9','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Parents Receiving Messages and Conducting Structured Activities at Home','Count number of parents received 2nd onboarding
Target: # Message sent - # Message failed to send
Actual: # Message opened','Pingtar Chatbot',null),
('PPI-137','PPI','Number of parents who received weekly instructional messages','TPL2.1.2.PCK-O.10','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Parents Receiving Messages and Conducting Structured Activities at Home','Count number of parents received weekly instructional message
Average
Target: # Content sent
Actual: # Content sent - # Content failed to send','Attendance',null),
('PPI-138','PPI','Number of parents who opened the HBNA message (open rate)','TPL2.1.2.PCK-O.11','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Parents Receiving Messages and Conducting Structured Activities at Home','Count number of parents opened the message from chatbot
Average
Target: # Content sent - # Content failed to send
Actual: # Contents opened','Pingtar Chatbot',null),
('PPI-139','PPI','Number of parents who clicked on the HBNA content (click rate)','TPL2.1.2.PCK-O.12','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Parents Receiving Messages and Conducting Structured Activities at Home','Count number of parents clicked the content
Average
Target: # Content sent - # Content failed to send
Actual: # Contents clicked','Pingtar Chatbot',null),
('PPI-140','PPI','Number of numeracy activities conducted by parents at home per month','TPL2.1.2.PCK-O.13','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Parents Receiving Messages and Conducting Structured Activities at Home','Count number numeracy activities reported conducted by parents at home with their children
The number of activities is taken from the number of participants who answered the survey under the activity criteria with the minimum number for that activity category.…','Pingtar Chatbot',null),
('PPI-141','PPI','Number of parents who demonstrated understanding of the HBNA content','TPL2.1.2.PCK-O.14','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Pedagogical Content Knowledge (PCK) Home-Based Numeracy Activity (HBNA) (J-PAL) Lever','TPL2.1.2','Output','Parents Receiving Messages and Conducting Structured Activities at Home','Count number of parents reported understood the HBNA content
Target: # Survey participants for the question "Apakah cara bermainnya mudah diikuti?"
Aktual: # Survey participants who answered the question "Apakah cara bermainnya mudah diikuti?" dengan "Sangat m…','Pingtar Chatbot',null),
('PPI-142','PPI','Percentage increase literacy and numeracy scores','TPL2.1.3.PANDAI-IMP.1','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Impact','Improved foundational literacy and numeracy proficiency among early grade students','Percent increase in literacy scores refers to percentage change (delta) in the proportion of students who got at least 60 per cent
correct answers for reading comprehension questions in EGRA sub-tasks (therefore falling into the category of ‘reading with
compr…',null,null),
('PPI-143','PPI','Percentage of trained teachers with increased knowledge on structured pedagogy','TPL2.1.3.PANDAI-OC.1','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Outcome','Teachers increase their knowledge on structured pedagogy in foundational literacy and numeracy',null,null,null),
('PPI-144','PPI','Percentage of trained teachers have increase knowledge on use of digital assessment data','TPL2.1.3.PANDAI-OC.2','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Outcome','Teachers'' increase knowledge to use the data to inform action for low performing students',null,null,null),
('PPI-145','PPI','Percentage of trained school principals and teachers use digital student performance data to prepare action plan','TPL2.1.3.PANDAI-OC.3','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Outcome','School principals & teachers collaboratively develop action plans to support low-performing students',null,null,null),
('PPI-146','PPI','Number of District staff supported for evidence-based planning and budgeting and to promote district scale up','TPL2.1.3.PANDAI-OC.4','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Outcome','School performance data presented and referenced during district planning (i.e. Musrenbang) sessions',null,null,null),
('PPI-147','PPI','Percentage of trained teachers use digital student performance data to inform remedial action','TPL2.1.3.PANDAI-O.1','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Output','Digital student performance data is collected regularly',null,null,null),
('PPI-148','PPI','Number of modules developed/co-created','TPL2.1.3.PANDAI-O.2','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Output','Teachers trained and coached in applying structured pedagogy in foundational literacy numeracy',null,null,null),
('PPI-149','PPI','Number of teachers trained','TPL2.1.3.PANDAI-O.3','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Output','Teachers trained and coached in applying structured pedagogy in foundational literacy numeracy',null,null,null),
('PPI-150','PPI','Number of teachers mentored','TPL2.1.3.PANDAI-O.4','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Output','Teachers trained and coached in applying structured pedagogy in foundational literacy numeracy',null,null,null),
('PPI-151','PPI','Number of modules developed/co-created','TPL2.1.3.PANDAI-O.5','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Output','Teachers trained and coached in applying structured pedagogy in foundational literacy numeracy',null,null,null),
('PPI-152','PPI','Available tech enabled learning diagnostics for formative assessment','TPL2.1.3.PANDAI-O.6','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Output','Teacher trained on tech-enabled student assessment, covering operationalization and the use of assessment instruments to support low-performing students',null,null,null),
('PPI-153','PPI','Number of teachers, principals and supervisors trained','TPL2.1.3.PANDAI-O.7','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Output','Teacher trained on tech-enabled student assessment, covering operationalization and the use of assessment instruments to support low-performing students',null,null,null),
('PPI-154','PPI','Number of teachers trained','TPL2.1.3.PANDAI-O.8','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Output','Teacher trained on data analysis, differentiated instruction, and remedial strategies for low performing students',null,null,null),
('PPI-155','PPI','Number of teachers coached','TPL2.1.3.PANDAI-O.9','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Output','Teacher trained on data analysis, differentiated instruction, and remedial strategies for low performing students',null,null,null),
('PPI-156','PPI','Number of school principals participated','TPL2.1.3.PANDAI-O.10','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Output','School principals and teachers participated in data-to-action collaborative workshop for classroom and school improvemen',null,null,null),
('PPI-157','PPI','Number of District officials participated','TPL2.1.3.PANDAI-O.11','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Output','District officials participated in joint monitoring visits',null,null,null),
('PPI-158','PPI','Number of District officials participated','TPL2.1.3.PANDAI-O.12','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','FAASTER/PANDAI (UNICEF) Lever','TPL2.1.3','Output','District officials participated in stakeholder meetings',null,null,null),
('PPI-159','PPI','Number of invited participants in the training session','TPL2.1.4.DDSL-O.1','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Data Driven School Leadership (DDSL) (WVI) Lever','TPL2.1.4','Output','Conduct training for school leaders, teachers, and school operators','Number of invited participants to the training session','Participant attendance form',null),
('PPI-160','PPI','Number of participants attended the training session','TPL2.1.4.DDSL-O.2','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Data Driven School Leadership (DDSL) (WVI) Lever','TPL2.1.4','Output','Conduct training for school leaders, teachers, and school operators','The number of participants (non-double counted) who are recorded as having attended all training sessions in full, covering both morning and afternoon sessions on every training day, from the first day to the last day of the training. Participants who missed a…','Participant attendance form',null)
on conflict (id) do update set
  type=excluded.type, name=excluded.name, code=excluded.code, unit=excluded.unit,
  calc=excluded.calc, t2030=excluded.t2030, strategy_map=excluded.strategy_map,
  outcome=excluded.outcome, accountability=excluded.accountability, program=excluded.program,
  details=excluded.details, toc_foundation=excluded.toc_foundation,
  toc_foundation_code=excluded.toc_foundation_code, portfolio=excluded.portfolio,
  portfolio_code=excluded.portfolio_code, project=excluded.project,
  project_code=excluded.project_code, level=excluded.level,
  result_statement=excluded.result_statement, definition=excluded.definition,
  mov=excluded.mov, period=excluded.period;

select type, count(*) as indikator from public.indicators group by type order by type;
