-- =====================================================================
-- SIGMA — struktur indikator: OPI (80 indikator)
--
-- Bagian dari seed_1. Dipecah menjadi tiga berkas agar tiap berkas nyaman
-- ditempel ke SQL Editor tanpa perlu dipotong manual.
-- Jalankan berurutan: 1a, 1b, 1c. Aman dijalankan berulang.
--
-- Catatan teknis: beberapa teks indikator memuat tanda titik koma. Karakter
-- itu ditulis sebagai chr(59) dan disambung dengan tanda pipa ganda, sehingga
-- tidak ada satu pun titik koma di dalam literal string. Berkas tetap utuh
-- walaupun editor memisah perintah berdasarkan titik koma.
-- =====================================================================

insert into public.indicators (id,type,name,code,unit,calc,t2030,strategy_map,outcome,accountability,program,details,toc_foundation,toc_foundation_code,portfolio,portfolio_code,project,project_code,level,result_statement,definition,mov,period) values
('OPI-001','OPI','Percentage of children in TF-operated Rumah Anak Sigap (RAS) centers are developmentally on-track',null,'Percent','Annual',0.8,'Beneficiaries & Stakeholders','Early stimulation & parenting are mainstreamed through all avenue','LE','ECED','ECED',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-002','OPI','Number of a measurement tool for ECD age 0-3 is available and adopted by government',null,'Number','Annual',2.0,'Beneficiaries & Stakeholders','Early stimulation & parenting are mainstreamed through all avenue','PA','ECED','ECED',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-003','OPI','Number of the policy level for parenting and early stimulation (national level)',null,'Number','Annual',3.0,'Beneficiaries & Stakeholders','Early stimulation & parenting are mainstreamed through all avenue','PA','ECED','ECED',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-004','OPI','Percentage of partner districts with regulations for parenting and early stimulation'||chr(59)||' Number of districts receiving awareness campaign',null,'Percent','Annual',0.8,'Beneficiaries & Stakeholders','Early stimulation & parenting are mainstreamed through all avenue','LE','ECED','ECED',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-005','OPI','Number of members in the coalition for COE in research & advocacy',null,'Number','Annual',10.0,'Beneficiaries & Stakeholders','Early stimulation & parenting are mainstreamed through all avenue','PA','PA, ECED','ECED',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-006','OPI','Total catalytic funding for early stimulation & parenting',null,'Text','Annual',1000000.0,'Beneficiaries & Stakeholders','Early stimulation & parenting are mainstreamed through all avenue','LE','ECED','ECED',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-007','OPI','Percentage of districts (villages) with the capacity to do stunting reduction programs',null,'Percent','Annual',0.7,'Beneficiaries & Stakeholders','Reducing of stunting prevalence','LE','ECED','Stunting 1.0',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-008','OPI','Number of national policy enacted to support stunting reduction',null,'Number','Annual',10.0,'Beneficiaries & Stakeholders','Reducing of stunting prevalence','LE','ECED','Stunting 1.0',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-009','OPI','Percentage of students in partner schools acquire mastery in literacy and numeracy by respective grade',null,'Percent','Annual',0.8,'Beneficiaries & Stakeholders','Improved literacy & numeracy','LE','BE','BE',null,null,'Basic Education (BE)',null,null,null,null,null,null,null,null),
('OPI-010','OPI','Number of districts implement PINTAR model',null,'Number','Annual',30.0,'Beneficiaries & Stakeholders','Improved literacy & numeracy','LE','BE','BE',null,null,'Basic Education (BE)',null,null,null,null,null,null,null,null),
('OPI-011','OPI','Percentage of partner districts with regulations for literacy & numeracy',null,'Percent','Annual',0.8,'Beneficiaries & Stakeholders','Improved literacy & numeracy','LE','BE','BE',null,null,'Basic Education (BE)',null,null,null,null,null,null,null,null),
('OPI-012','OPI','Total catalytic funding for literacy & numeracy',null,'Text','Annual',2000000.0,'Beneficiaries & Stakeholders','Improved literacy & numeracy','LE','BE','BE',null,null,'Basic Education (BE)',null,null,null,null,null,null,null,null),
('OPI-013','OPI','Percentage of A national numeracy initiative implemented',null,'Percent','Annual',1.0,'Beneficiaries & Stakeholders','Improved literacy & numeracy','LE','BE','BE',null,null,'Basic Education (BE)',null,null,null,null,null,null,null,null),
('OPI-014','OPI','Percentage of recommendations on school monitoring system (APS) presented to the national government',null,'Percent','Annual',1.0,'Beneficiaries & Stakeholders','Improved national and sub-national policy climate for literacy and numeracy: APS-like monitoring system on school quality is adapted by national government'||chr(59)||' 80% of partner districts have regulation fo…','LE','BE','BE',null,null,'Basic Education (BE)',null,null,null,null,null,null,null,null),
('OPI-015','OPI','Percentage of a national system for new teacher placement is implemented',null,'Percent','Annual',1.0,'Beneficiaries & Stakeholders','Improved literacy & numeracy','LE','BE','BE',null,null,'Basic Education (BE)',null,null,null,null,null,null,null,null),
('OPI-016','OPI','Percentage of fellows employed or start their own initiatives in development sectors < 4 months after graduation',null,'Percent','Annual',0.7,'Beneficiaries & Stakeholders','Increased importance of leadership development in HD sector','LDS','Fellowship','Fellowship',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-017','OPI','Percentage of Tanoto scholars show evidence of soft skill development and values',null,'Percent','Annual',0.8,'Beneficiaries & Stakeholders','Increased importance of leadership development in HD sector','LDS','TELADAN','TELADAN',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-018','OPI','Percentage of Tanoto scholars employed within 6 months of graduation (by cohort)',null,'Percent','Annual',1.0,'Beneficiaries & Stakeholders','Leaders contribute to the community and country','LDS','TELADAN','TELADAN',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-019','OPI','Percentage of Tanoto scholars conduct pay-it-forward, 3 years after graduation',null,'Percent','Annual',0.3,'Beneficiaries & Stakeholders','Leaders contribute to the community and country','LDS','TELADAN','TELADAN',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-020','OPI','Number of universities adopt TELADAN leadership and soft skills development model/modul',null,'Number','Cumulative',5.0,'Beneficiaries & Stakeholders','Increased importance of leadership development in HD sector','LDS','TELADAN','TELADAN',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-021','OPI','Number of caregivers reached',null,'Number','Cumulative',5000000.0,'Beneficiaries & Stakeholders','Beneficiaries contribute to the community and country','LE','ECED','Stunting 1.0',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-022','OPI','Number of teachers reached',null,'Number','Cumulative',100000.0,'Beneficiaries & Stakeholders','Beneficiaries contribute to the community and country','LE','BE','BE',null,null,'Basic Education (BE)',null,null,null,null,null,null,null,null),
('OPI-023','OPI','Number of children 0-3 reached by RAS',null,'Number','Cumulative',10000.0,'Beneficiaries & Stakeholders','Beneficiaries contribute to the community and country','LE','ECED','ECED',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-024','OPI','Number of government officials reached',null,'Number','Annual',50000.0,'Beneficiaries & Stakeholders','Beneficiaries contribute to the community and country','PA','GCB','CSD',null,null,'Government Capacity Building (GCB)',null,null,null,null,null,null,null,null),
('OPI-025','OPI','Number of scholars reached',null,'Number','Cumulative',10000.0,'Beneficiaries & Stakeholders','Beneficiaries contribute to the community and country','LDS','TELADAN','TELADAN',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-026','OPI','Number of public reached through comms program',null,'Number','Annual',20000000.0,'Beneficiaries & Stakeholders','Beneficiaries contribute to the community and country','PA','Communication','Communication',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-027','OPI','Percentage of alumni engaged that receive of alumni newsletter (responses rate)',null,'Percent','Annual',0.3,'Beneficiaries & Stakeholders','Beneficiaries contribute to the community and country','PA','Communication','Communication',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-028','OPI','Number of Policy Quality Index in Education (MOECRT) and Health (MOH) sectors',null,'Number','Annual',80.0,'Beneficiaries & Stakeholders','Government demonstrates enhanced capacity and financial commitment to improve human capital development'||chr(59)||' 10% government leaders drive action in early stimulation, parenting, literacy, and numeracy','PA','PA','PA',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-029','OPI','Level of stakeholders perception',null,'Text','Annual',null,'Beneficiaries & Stakeholders','Tanoto Foundation serves as a thought and catalytic leader for human capital development within the social ecosystem','PA','PA','PA',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-030','OPI','Number of publications, citation and reference',null,'Number','Annual',30.0,'Beneficiaries & Stakeholders','Tanoto Foundation serves as a thought and catalytic leader for human capital development within the social ecosystem','PA','PA','PA',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-031','OPI','Number of high-level forum on national or regional level with TF representation as a speaker bringing advocacy agenda',null,'Number','Annual',12.0,'Beneficiaries & Stakeholders','Tanoto Foundation serves as a thought and catalytic leader for human capital development within the social ecosystem','PA','Communication','Communication',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-032','OPI','Zero major audit findings',null,'Number','Annual',0.0,'Financial','Operation excellence & sustainable growth','FATLC','FATLC','All',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-033','OPI','Budget control TF Indo budget effectiveness',null,'Percent','Annual',1.0,'Financial','Operation excellence & sustainable growth','FATLC','FATLC','FATLC',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-034','OPI','Efficient budget absorption: Overhead Cost',null,'Percent','Annual',null,'Financial','Operation excellence & sustainable growth','FATLC','FATLC','FATLC',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-035','OPI','Unit cost for leadership development & scholarship program below agreed threshold: IDR Average tuition fee/scholar/semester',null,'Text','Annual',7100000.0,'Financial','Operation excellence & sustainable growth','LDS','TELADAN','TELADAN',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-036','OPI','Unit cost for leadership development & scholarship program below agreed threshold: IDR Recruitment cost / scholar',null,'Text','Annual',2000000.0,'Financial','Operation excellence & sustainable growth','LDS','TELADAN','TELADAN',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-037','OPI','Number of kaizen projects completed and operationalized',null,'Number','Annual',5.0,'Internal Process','Operation excellence & sustainable growth','SPP','SPP','SPP',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-038','OPI','Regrettable attrition rate due to culture (through a trust-based organization with a global mindset)',null,'Percent','Annual',null,'Learning & Growth','Operation excellence & sustainable growth','HRD','HRD','HR',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-039','OPI','Critical vacancy fulfilment rate',null,'Percent','Annual',0.9,'Learning & Growth','Operation excellence & sustainable growth','HRD','HRD','HR',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-040','OPI','Key succession leadership in-place and key subject-matter expertise available',null,'Percent','Annual',1.0,'Learning & Growth','Operation excellence & sustainable growth','HRD','HRD','HR',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-041','OPI','Percentage of completion a measurement tool for ECD age 0-3 is available and adopted by government',null,'Percent','Annual',1.0,'Beneficiaries & Stakeholders','Early stimulation & parenting are mainstreamed through all avenue','LE','ECED','ECED',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-042','OPI','Percentage of completion the policy level for parenting and early stimulation (national level)',null,'Percent','Annual',1.0,'Beneficiaries & Stakeholders','Early stimulation & parenting are mainstreamed through all avenue','LE','ECED','ECED',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-043','OPI','Percentage of ECED Council community in-place',null,'Percent','Annual',1.0,'Beneficiaries & Stakeholders','Improved national and sub-national policy climate for early stimulation and parenting: Parenting and early stimulation policies are issued by national Government'||chr(59)||' 40% of our partner district governmen…','LE','ECED','ECED Council',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-044','OPI','Number of institutions that give concrete commitment to ECED issues',null,'Number','Annual',5.0,'Beneficiaries & Stakeholders','Implementation of early stimulation & parenting through catalytic funding','LE','ECED','ECED',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-045','OPI','Number of institutions that give concrete commitment to Literacy and Numeracy issues',null,'Number','Annual',5.0,'Beneficiaries & Stakeholders','Improved literacy & numeracy','LE','BE','BE',null,null,'Basic Education (BE)',null,null,null,null,null,null,null,null),
('OPI-046','OPI','Percentage government leaders drive action in early stimulation, parenting, literacy, and numeracy
SDG AI and CSD supports the achievement of Advocacy Goal 1 and 2',null,'Percent','Annual',1.0,'Beneficiaries & Stakeholders','Government demonstrates enhanced capacity and financial commitment to improve human capital development'||chr(59)||' 10% government leaders drive action in early stimulation, parenting, literacy, and numeracy','PA','PA, ECED, BE','ECED, BE',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-047','OPI','Level of stakeholders perception',null,'Text','Annual',null,'Beneficiaries & Stakeholders','Increased awareness, knowledge, resources and partnership for human capital development','PA','Thought and Catalityc Leadership','Thought and Catalityc Leadership',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-048','OPI','Number of publications, citation and reference',null,'Number','Annual',30.0,'Beneficiaries & Stakeholders','Tanoto Foundation serves as a thought and catalytic leader for human capital development within the social ecosystem','PA','Communication','Thought and Catalityc Leadership',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-049','OPI','Number of high-level forum on national or regional level with TF representation as a speaker bringing advocacy agenda',null,'Number','Annual',12.0,'Beneficiaries & Stakeholders','Increased awareness, knowledge, resources and partnership for human capital development','SPP','Thought and Catalityc Leadership','Thought and Catalityc Leadership',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-050','OPI','Number of reach harnessed from media',null,'Number','Annual',100000000.0,'Beneficiaries & Stakeholders','Tanoto Foundation serves as a thought and catalytic leader for human capital development within the social ecosystem','PA','PA','PA',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-051','OPI','Number of alumni engaged (annual)',null,'Number','Annual',500.0,'Beneficiaries & Stakeholders','Increased awareness, knowledge, resources and partnership for human capital development','PA','Communication','PA',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-052','OPI','Percentage of LE cost saving',null,'Percent','Annual',0.03,'Financial','Operation excellence & sustainable growth','FATLC','FATLC','FATLC',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-053','OPI','Unit cost for leadership development & scholarship program below agreed threshold: IDR Leadership Dev. Cost /scholar /cohort',null,'Text','Annual',12000000.0,'Financial','Operation excellence & sustainable growth','LDS','TELADAN','Leadership Development',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-054','OPI','Number of CI projects completed and operationalized',null,'Number','Annual',5.0,'Internal Process','Operation excellence & sustainable growth','SPP','SPP','SPP',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-055','OPI','Number of MCHN policy recommendations provided to and/or adopted by national government',null,'Number','Annual',20.0,'Beneficiaries & Stakeholders','Strengthened institutions, policies, and people related to national stunting reduction initiatives','LE','MDTF','1. MDTF
2. SATUSEHAT
3. MBG',null,null,'Maternal and Child Health & Nutrition (MCHN)',null,null,null,null,null,null,null,null),
('OPI-056','OPI','Percentage of ALPHA and SNAP-ON program (SINERGI) inception milestones successfully completed',null,'Percent','Annual',null,'Beneficiaries & Stakeholders','70% of partner districts have the capacity to do the stunting reduction program','LE','ALPHA, SNAP-ON','ALPHA, SNAP-ON',null,null,'Maternal and Child Health & Nutrition (MCHN)',null,null,null,null,null,null,null,null),
('OPI-057','OPI','Percentage of data system (operational POPS) at village level established and data collected/updated',null,'Percent','Annual',1.0,'Beneficiaries & Stakeholders','70% of partner districts have the capacity to do the stunting reduction program','LE','Stunting Reduction','Stunting 2.0',null,null,'Maternal and Child Health & Nutrition (MCHN)',null,null,null,null,null,null,null,null),
('OPI-058','OPI','Number of villages adopted integrated model for acceleration stunting reduction',null,'Number','Annual',null,'Beneficiaries & Stakeholders','70% of partner districts have the capacity to do the stunting reduction program','LE','PASTI','PASTI 2.0',null,null,'Maternal and Child Health & Nutrition (MCHN)',null,null,null,null,null,null,null,null),
('OPI-059','OPI','Number of Rumah Anak SIGAP as CoE and/or newly built',null,'Number','Annual',50.0,'Beneficiaries & Stakeholders','80% children in our centers developmentally on-track according to CREDI','LE','RAS','RAS',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-060','OPI','Number of PES national and regional policies developed or strengthened',null,'Number','Cumulative',17.0,'Beneficiaries & Stakeholders','Improved national and sub-national policy climate for early stimulation and parenting: Parenting and early stimulation policies are issued by national Government'||chr(59)||' 40% of our partner district governmen…','LE','BE','Adv Goal 1',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-061','OPI','Percentage of service model readiness for integrating stimulation into primary health services (ILP)',null,'Percent','Annual',1.0,'Beneficiaries & Stakeholders','Improved national and sub-national policy climate for early stimulation and parenting: Parenting and early stimulation policies are issued by national Government'||chr(59)||' 40% of our partner district governmen…','LE','ECED','SPRING',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-062','OPI','Proxy indicator 2026: 
Number new levers program with compliance to program design',null,'Number','Annual',4.0,'Beneficiaries & Stakeholders','4 levers shows the evidence of effective improvements in literacy and numeracy','LE','BE','New Levers:
1. DDSL
2. Numeracy Parent
3. Numeracy Teacher
4. PPG - Teaching Practicum
5. FAASTER - Structured Pedagogy…',null,null,'Basic Education (BE)',null,null,null,null,null,null,null,null),
('OPI-063','OPI','Number of institutions that give concrete commitment to BE issues',null,'Number','Annual',2.0,'Beneficiaries & Stakeholders','Expansion of partner district through catalytic funding','LE','BE','1. PINTAR Replication
2. Partnership',null,null,'Basic Education (BE)',null,null,null,null,null,null,null,null),
('OPI-064','OPI','Number of local innovation adopted by schools or governments or private sectors',null,'Number','Annual',15.0,'Beneficiaries & Stakeholders','30 districts sustain/scale the implementation of teaching & learning improvement programs','LE','BE','PINTAR 1.0',null,null,'Basic Education (BE)',null,null,null,null,null,null,null,null),
('OPI-065','OPI','Number of national and regional policies related to LN developed or strengthened',null,'Number','Cumulative',31.0,'Beneficiaries & Stakeholders','Improved national and sub-national policy climate for literacy and numeracy: APS-like monitoring system on school quality is adapted by national government'||chr(59)||' 80% of partner districts have regulation fo…','LE','BE','Adv Goal 2',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-066','OPI','Number of TELADAN delivery model (LS, LO, PP) transformation implemented (incl. fully developed, launched, tested and implemented leadership competency assessment tools)',null,'Number','Annual',4.0,'Beneficiaries & Stakeholders','Tanoto Scholars show evidence of the development of soft skills and values','LDS','TELADAN','TELADAN',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-067','OPI','TELADAN maintain performance of employment and skill development',null,'Percent','Annual',1.0,'Beneficiaries & Stakeholders','Tanoto Scholars show evidence of the development of soft skills and values','LDS','TELADAN','TELADAN',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-068','OPI','Level of government engagement and maintenance',null,'Percent','Annual',1.0,'Beneficiaries & Stakeholders','Government demonstrates enhanced capacity and financial commitment to improve human capital development'||chr(59)||' 10% government leaders drive action in early stimulation, parenting, literacy, and numeracy','PA','PA','GEA',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-069','OPI','Number of civil servants participated in capacity building activities, with at least PES or LN content',null,'Number','Annual',10000.0,'Beneficiaries & Stakeholders','Government demonstrates enhanced capacity and financial commitment to improve human capital development'||chr(59)||' 10% government leaders drive action in early stimulation, parenting, literacy, and numeracy','PA','GCB','CSD',null,null,'Government Capacity Building (GCB)',null,null,null,null,null,null,null,null),
('OPI-070','OPI','Number of NPO trained (proxy Indicator 2026)',null,'Number','Annual',7.0,'Beneficiaries & Stakeholders','Tanoto Foundation serves as a thought and catalytic leader for human capital development within the social ecosystem','SPP','Partnership','Partnership',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-071','OPI','Number of public advocacy campaign executed on the national and subnational level',null,'Number','Annual',2.0,'Beneficiaries & Stakeholders','Tanoto Foundation serves as a thought and catalytic leader for human capital development within the social ecosystem','PA','Communication','Communication',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-072','OPI','Number of reach harnessed from media',null,'Number','Annual',100000000.0,'Beneficiaries & Stakeholders','Tanoto Foundation serves as a thought and catalytic leader for human capital development within the social ecosystem','PA','Communication','Communication',null,null,'Policy and Advocacy (PA)',null,null,null,null,null,null,null,null),
('OPI-073','OPI','Number of alumni engaged to OpEd, as speaker/resource person, events, FGDs',null,'Number','Cumulative',250.0,'Beneficiaries & Stakeholders','Beneficiaries contribute to the community and country','LDS','TELADAN','Communication',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-074','OPI','Number of TELADAN alumni contributed back',null,'Number','Annual',30.0,'Beneficiaries & Stakeholders','Beneficiaries contribute to the community and country','LDS','TELADAN','Communication',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-075','OPI','Number of high profile alumni engaged',null,'Number','Annual',10.0,'Beneficiaries & Stakeholders','Beneficiaries contribute to the community and country','LDS','TELADAN','Communication',null,null,'Leadership Development and Scholarship (LDS)',null,null,null,null,null,null,null,null),
('OPI-076','OPI','Unit cost for Rumah Anak SIGAP program below agreed threshold (IDR/child/day)',null,'Text','Annual',null,'Financial','Operation excellence & sustainable growth','LE','ECED','RAS',null,null,'Early Childhood Education and Development (ECED)',null,null,null,null,null,null,null,null),
('OPI-077','OPI','Number of CI projects completed and operationalized',null,'Number','Annual',12.0,'Internal Process','Operation excellence & sustainable growth','SPP','KM','KM',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-078','OPI','Percentage of completion strategic system alignment established and implemented',null,'Percent','Annual',1.0,'Internal Process','Operation excellence & sustainable growth','SPP','SPP, MLE','SPP, MLE',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-079','OPI','Percentage of One-TF operating system established',null,'Percent','Annual',1.0,'Internal Process','Operation excellence & sustainable growth','SPP','SPP','SPP',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null),
('OPI-080','OPI','Percentage of completion development of capability framework',null,'Percent','Annual',1.0,'Learning & Growth','Operation excellence & sustainable growth','HRD','HRD','HR',null,null,'Corporate / Cross-cutting',null,null,null,null,null,null,null,null)
on conflict (id) do update set
  type=excluded.type, name=excluded.name, code=excluded.code, unit=excluded.unit,
  calc=excluded.calc, t2030=excluded.t2030, strategy_map=excluded.strategy_map,
  outcome=excluded.outcome, accountability=excluded.accountability, program=excluded.program,
  details=excluded.details, toc_foundation=excluded.toc_foundation,
  toc_foundation_code=excluded.toc_foundation_code, portfolio=excluded.portfolio,
  portfolio_code=excluded.portfolio_code, project=excluded.project,
  project_code=excluded.project_code, level=excluded.level,
  result_statement=excluded.result_statement, definition=excluded.definition,
  mov=excluded.mov, period=excluded.period;

select type, count(*) as indikator from public.indicators group by type order by type;
