-- =====================================================================
-- SIGMA — struktur indikator: PPI bagian 2 (147 indikator)
--
-- Bagian dari seed_1. Dipecah menjadi tiga berkas agar tiap berkas nyaman
-- ditempel ke SQL Editor tanpa perlu dipotong manual.
-- Jalankan berurutan: 1a, 1b, 1c. Aman dijalankan berulang.
--
-- Catatan teknis: beberapa teks indikator memuat tanda titik koma. Karakter
-- itu ditulis sebagai chr(59) dan disambung dengan tanda pipa ganda, sehingga
-- tidak ada satu pun titik koma di dalam literal string. Berkas tetap utuh
-- walaupun editor memisah perintah berdasarkan titik koma.
-- =====================================================================

insert into public.indicators (id,type,name,code,unit,calc,t2030,strategy_map,outcome,accountability,program,details,toc_foundation,toc_foundation_code,portfolio,portfolio_code,project,project_code,level,result_statement,definition,mov,period) values
('PPI-161','PPI','Number of participants attended the morning training session','TPL2.1.4.DDSL-O.3','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Data Driven School Leadership (DDSL) (WVI) Lever','TPL2.1.4','Output','Conduct training for school leaders, teachers, and school operators','The number of participants who are recorded as present and have signed the attendance register during the morning session of the training (from the opening session until before the lunch break) on each training day.','Participant attendance form',null),
('PPI-162','PPI','Number of participants attended the afternoon training session','TPL2.1.4.DDSL-O.4','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Data Driven School Leadership (DDSL) (WVI) Lever','TPL2.1.4','Output','Conduct training for school leaders, teachers, and school operators','The number of unique participants who are recorded as present and have signed the attendance register during the afternoon session of the training (from after the lunch break until the closing session) on each training day.','Participant attendance form',null),
('PPI-163','PPI','Number of participants attended the coaching to deepening school''s action plan (Coaching I)','TPL2.1.4.DDSL-O.5','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Data Driven School Leadership (DDSL) (WVI) Lever','TPL2.1.4','Output','Conduct training for school leaders, teachers, and school operators','Number of participant attended all the coaching session','Participant attendance form',null),
('PPI-164','PPI','Number of participants attended the coaching on school plan development workshop (Coaching II)','TPL2.1.4.DDSL-O.6','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Data Driven School Leadership (DDSL) (WVI) Lever','TPL2.1.4','Output','Conduct training for school leaders, teachers, and school operators','Number of participant attended all the coaching session','Participant attendance form',null),
('PPI-165','PPI','Number of training session conducted','TPL2.1.4.DDSL-O.7','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Data Driven School Leadership (DDSL) (WVI) Lever','TPL2.1.4','Output','Training session delivered to school leaders, teachers, and school operator','Number of training session conducted','Participant attendance form',null),
('PPI-166','PPI','Number of coaching session conducted','TPL2.1.4.DDSL-O.8','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Data Driven School Leadership (DDSL) (WVI) Lever','TPL2.1.4','Output','Coaching session delivered to school leaders, teachers, and school operators','Number of training session conducted','Participant attendance form',null),
('PPI-167','PPI','Percentage of higher-grade teachers that meet teaching quality in active learning and creating HOTS question','TPL2.1.5.OIKN-OC.1','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Outcome','Improved teaching practices in active learning, creating HOTS question, and specific subject skills (Science, Math, and Bahasa Indonesia)','Percentage of higher-grade teachers (Grades 4–6) scoring at or above the minimum competency threshold (≥ 75% rubric score) on an observation rubric measuring active learning practices and HOTS question construction.','Classroom observation checklists, self-assessment forms.',null),
('PPI-168','PPI','Percentage of higher-grade teachers that meet teaching quality practices in Science, Math, and Bahasa Indonesia pedagogy','TPL2.1.5.OIKN-OC.2','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Outcome','Improved teaching practices in active learning, creating HOTS question, and specific subject skills (Science, Math, and Bahasa Indonesia)','The percentage of higher-grade teachers (Grades 4–6) who achieve the minimum competency threshold (≥75 percent of total rubric score) on subject-specific pedagogical quality standards in Science, Mathematics, and Bahasa Indonesia, assessed through classroom ob…','Classroom observation checklists, self-assessment forms.',null),
('PPI-169','PPI','Percentage point increase in teachers'' knowledge score in active learning and creating HOTS questions','TPL2.1.5.OIKN-IMO.1','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Intermediate Outcome','Increased teacher knowledge in active learning, creating HOTS question, specific subject skills (higher-grade teachers)','The average percentage point difference between teachers’ post-test and pre-test scores','Classroom observation checklists, self-assessment forms.',null),
('PPI-170','PPI','Percentage point increase in teachers'' knowledge score in science, Math, and Bahasa Indonesia
pedagogy','TPL2.1.5.OIKN-IMO.2','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Intermediate Outcome','Increased teacher knowledge in active learning, creating HOTS question, specific subject skills (higher-grade teachers)','The average percentage point increase in teachers’ subject-specific pedagogical knowledge from pre-test to post-test','Classroom observation checklists, self-assessment forms.',null),
('PPI-171','PPI','Number of teachers participated in active learning training and creating HOTS (Higher Order Thinking Skills) question','TPL2.1.5.OIKN-O.1','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','Teachers are trained and mentored in general pedagogy includes active learning, creating HOTS question, specific subject skills (higher-grade teachers)','Number of unique teachers who are registered and attend at least 80 percent of the total scheduled training hours/sessions for Active Learning and HOTS training within the reporting period.','Classroom observation checklists, self-assessment forms.',null),
('PPI-172','PPI','Number of teachers receiving mentorship in active learning and creating HOTS (Higher Order ThinkingSkills) question','TPL2.1.5.OIKN-O.2','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','Teachers are trained and mentored in general pedagogy includes active learning, creating HOTS question, specific subject skills (higher-grade teachers)','Number of unique teachers who receive at least one documented mentoring session focused on implementing active learning practices and/or developing HOTS questions, during the reporting period.','Classroom observation checklists, self-assessment forms.',null),
('PPI-173','PPI','Number of teachers participated in science, math, and bahasa indonesia pedagogy training','TPL2.1.5.OIKN-O.3','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','Teachers are trained and mentored in general pedagogy includes active learning, creating HOTS question, specific subject skills (higher-grade teachers)','Number of unique teachers who attend the session','Classroom observation checklists, self-assessment forms.',null),
('PPI-174','PPI','Number of teachers receiving mentorship in the science, math, and bahasa indonesia pedagogy','TPL2.1.5.OIKN-O.4','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','Teachers are trained and mentored in general pedagogy includes active learning, creating HOTS question, specific subject skills (higher-grade teachers)','Number of unique teachers who receive mentoring session','Classroom observation checklists, self-assessment forms.',null),
('PPI-175','PPI','Number of training in academic supervision for school principals','TPL2.1.5.OIKN-O.5','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','Conducting training and mentoring sessions on academic supervision for school
principals','The total number of distinct academic supervision training events formally conducted for school principals within the reporting period.','Attendance form',null),
('PPI-176','PPI','Number of mentoring in academic supervision for school principals','TPL2.1.5.OIKN-O.6','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','Conducting training and mentoring sessions on academic supervision for school
principals','The total number of structured mentoring sessions delivered to school principals focused on strengthening academic supervision practices during the reporting period.','Attendance form',null),
('PPI-177','PPI','Percentage of school principals who frequently conduct academic supervision of teacher''s learning','TPL2.1.5.OIKN-IMO.3','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Intermediate Outcome','Increased school principal practice in learning academic supervisions','The percentage of school principals who conduct at least one structured academic supervision','Attendance form',null),
('PPI-178','PPI','Number school principal participated in academic supervision for learning training','TPL2.1.5.OIKN-O.7','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','School principals are trained and mentored in academic supervision for learning','Number of training conducted','Attendance form',null),
('PPI-179','PPI','Number of school principal receiving mentorship in academic supervision for learning','TPL2.1.5.OIKN-O.8','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','School principals are trained and mentored in academic supervision for learning','Number of mentoring conducted','Attendance form',null),
('PPI-180','PPI','Percentage of schools implementing and actively tracking student reading behaviors','TPL2.1.5.OIKN-OC.3','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Outcome','Improve reading culture at school','1. There are school-level regulations related to reading habit programs, including official decrees (SK) and circular letters that mandate schools to implement these reading initiatives.
Programs and activities in the School Work Plan (RKTS) support the develo…','School observation checklist',null),
('PPI-181','PPI','Percentage of schools where principals allocate resources (e.g., time, budget, staff) to develop andsupport a reading culture program','TPL2.1.5.OIKN-IMO.4','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Intermediate Outcome','Strengthened school management and principal support for reading culture programs, and increased teacher use of quality reading materials in classrooms','1. Allocate at least 1 hour per week for reading activities (or equivalent).
2. Provide funding for reading materials and reading events.
3. Employ staff (librarians)','Classroom observation checklists, self-assessment forms.',null),
('PPI-182','PPI','Percentage point Increase in teachers'' practice about utilizing quality reading materials in the classroom','TPL2.1.5.OIKN-IMO.5','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Intermediate Outcome','Strengthened school management and principal support for reading culture programs, and increased teacher use of quality reading materials in classrooms','1. Integrate reading materials into their daily or weekly lesson plans'||chr(59)||'
2. Differentiate reading materials to meet the needs of both struggling and advanced readers'||chr(59)||'
3. Encourage students to engage in independent or small group reading activities using the mat…','Attendance Form',null),
('PPI-183','PPI','Number of school principal participated in building reading culture at school training','TPL2.1.5.OIKN-O.9','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','School principal are trained and mentored in building reading culture at school, and teachers are trained and mentored in utilizing quality reading material in the classroom','Count school principals participating in training','Attendance Form',null),
('PPI-184','PPI','Number of school principals receiving mentorship in building reading culture at school','TPL2.1.5.OIKN-O.10','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','School principal are trained and mentored in building reading culture at school, and teachers are trained and mentored in utilizing quality reading material in the classroom','Count school principals participating in mentoring','Attendance Form',null),
('PPI-185','PPI','Number of teachers participated in the utilizing quality reading material training','TPL2.1.5.OIKN-O.11','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','School principal are trained and mentored in building reading culture at school, and teachers are trained and mentored in utilizing quality reading material in the classroom','Count teachers participating in training','Attendance Form',null),
('PPI-186','PPI','Number of teachers receiving mentorship in utilizing quality reading material','TPL2.1.5.OIKN-O.12','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','School principal are trained and mentored in building reading culture at school, and teachers are trained and mentored in utilizing quality reading material in the classroom','Count teachers participating in mentoring','Attendance Form',null),
('PPI-187','PPI','Number of training in building reading culture at school for school principals','TPL2.1.5.OIKN-O.13','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','Conducting training and mentoring sessions on building reading culture for school principals and utilizing quality reading material for teachers','Count school principals participating in training','Attendance Form',null),
('PPI-188','PPI','Number of mentoring in building reading culture at school for school principals','TPL2.1.5.OIKN-O.14','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','Conducting training and mentoring sessions on building reading culture for school principals and utilizing quality reading material for teachers','Count school principals participating in mentoring','Attendance Form',null),
('PPI-189','PPI','Number of training in the utilizing quality reading material training for teachers','TPL2.1.5.OIKN-O.15','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','Conducting training and mentoring sessions on building reading culture for school principals and utilizing quality reading material for teachers','Count teachers participating in training','Attendance Form',null),
('PPI-190','PPI','Number of mentoring in utilizing quality reading material for teachers','TPL2.1.5.OIKN-O.16','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','Conducting training and mentoring sessions on building reading culture for school principals and utilizing quality reading material for teachers','Count teachers participating in mentoring','Attendance Form',null),
('PPI-191','PPI','Percentage of school principals who frequently conduct academic supervision on reading culture','TPL2.1.5.OIKN-IMO.6','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Intermediate Outcome','Increased school principal practice in academic supervision on reading culture','This supervision is conducted once a month for each teacher and includes a checklist covering the following aspects. Each academic supervision will result in a follow-up action plan (RTL), which will be discussed during the school’s monthly meeting between the…','Classroom observation checklists, self-assessment forms.',null),
('PPI-192','PPI','Number school principal participated in academic supervision training for reading culture development','TPL2.1.5.OIKN-O.17','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','School principals are trained and mentored in academic supervision on reading culture','Count school principals participating in training','Attendance Form',null),
('PPI-193','PPI','Number of school principal receiving mentorship in academic supervision for reading culture','TPL2.1.5.OIKN-O.18','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','School principals are trained and mentored in academic supervision on reading culture','Count school principals participating in mentoring','Attendance Form',null),
('PPI-194','PPI','Number of training in reading culture academic supervision for school principals','TPL2.1.5.OIKN-O.19','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','Conducted training and mentoring sessions on reading culture academic supervision for school principals','Count school principals participating in training','Attendance Form',null),
('PPI-195','PPI','Number of mentoring in reading culture academic supervision for school principals','TPL2.1.5.OIKN-O.20','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Improvement Project - OIKN','TPL2.1.5','Output','Conducted training and mentoring sessions on reading culture academic supervision for school principals','Count school principals participating in mentoring','Attendance Form',null),
('PPI-196','PPI','Number of replication districts','TPL2.1.6.TR-O.1','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Training Replication','TPL2.1.6','Output','The programme expanded to additional districts, with new districts formally adopting and implementing the model as part of their local education strategy.','Number of new districts replicating PINTAR Program. Replication refers to the process of extending or expanding a program, or/and intervention into new districts outside the existing intervention area funded from district government','1. Signed Memorandum of Understanding (MoU) or Cooperation Agreement
2. Official government decree or endorsement letter',null),
('PPI-197','PPI','Total funding support replication support replication from government (IDR Mio)','TPL2.1.6.TR-O.2','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Training Replication','TPL2.1.6','Output','Local governments demonstrated ownership and sustainability commitment by allocating financial resources (IDR million) to replicate and scale the programme.','The total amount of financial support committed and/or disbursed by government entities to support program replication, measured in million Indonesian Rupiah (IDR Mio) during the reporting period. This includes budget allocations, grants, or co-funding specifi…','Co-funding agreements',null),
('PPI-198','PPI','Number of school principals trained (non-double counting)','TPL2.1.6.TR-O.3','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Training Replication','TPL2.1.6','Output','School principal capacity was strengthened, with unique school principals completing the programme training without double counting across reporting cycles.','The total number of school principals who participate in training session during the reporting period. Each individual principal is counted only once, even if they attend multiple trainings or sessions','Training attendance lists',null),
('PPI-199','PPI','Number of teachers trained (non-double counting)','TPL2.1.6.TR-O.4','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Training Replication','TPL2.1.6','Output','Teacher capacity was expanded, with unique teachers completing the programme training without duplication across sessions or reporting periods.','The total number of teachers who participate in training session during the reporting period. Each individual principal is counted only once, even if they attend multiple trainings or sessions','Training attendance lists',null),
('PPI-200','PPI','Number of partner districts with a formal policy commitment at the regional level (perbup, perwali, or any district regulations)','TPL2.1.7.APS-IMO.1','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Monitoring System (APS)','TPL2.1.7','Intermediate Outcome','Strengthened school performance monitoring and data-driven policy making','A partner district is counted under this indicator if it has an official, documented regulation at the district level (e.g., Peraturan Bupati [Perbup], Peraturan Walikota [Perwali], or equivalent) that explicitly governs the establishment or implementation of…',null,null),
('PPI-201','PPI','Number of partner districts with specific budget allocation for the monitoring system and its sustainability','TPL2.1.7.APS-IMO.2','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Monitoring System (APS)','TPL2.1.7','Intermediate Outcome','Strengthened school performance monitoring and data-driven policy making','A district qualifies under this indicator if it has a dedicated line item or clearly allocated budget within the district’s financial planning documents that supports the operation and sustainability of the school monitoring system. This includes funding for:…',null,null),
('PPI-202','PPI','Number of partner districts with a dedicated monitoring team (including IT staff for data visualization and data collectors)','TPL2.1.7.APS-IMO.3','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Monitoring System (APS)','TPL2.1.7','Intermediate Outcome','Strengthened school performance monitoring and data-driven policy making','A partner district meets this indicator if it has a formally assigned and functioning team responsible for the school monitoring system, which includes:

- Personnel for data collection
- IT or M&E staff who visualize and analyze data
- Staff or budget support…',null,null),
('PPI-203','PPI','Number of partner districts conduct data collection at least once a year','TPL2.1.7.APS-IMO.4','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Monitoring System (APS)','TPL2.1.7','Intermediate Outcome','Strengthened school performance monitoring and data-driven policy making','This indicator counts districts that carry out structured school-related data collection activities (e.g., related to school quality, learning outcomes, or teacher performance) at least once annually, using digital tool, as part of their monitoring system.',null,null),
('PPI-204','PPI','Number of partner districts using monitoring system data for decision-making at the regional level','TPL2.1.7.APS-I21OC.1','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Monitoring System (APS)','TPL2.1.7','Outcome','Strengthened school performance monitoring and data-driven policy making','A partner district is considered to meet this indicator if there is documented evidence (e.g. planning documents, policy adjustments, or budget revisions) that data generated from the monitoring system has been used to inform planning, budgeting, or policy dec…',null,null),
('PPI-205','PPI','Number of partner districts with a sustained monitoring system (i.e., all indicators above are fulfilled)','TPL2.1.7.APS-I21OC.2','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','School Monitoring System (APS)','TPL2.1.7','Outcome','Strengthened school performance monitoring and data-driven policy making','A district is counted under this indicator if it fulfills all five preceding indicators, demonstrating that it has:

- A formal policy/regulation on monitoring
- Specific budget allocation for the system
- A dedicated monitoring team
- Conducted data collectio…',null,null),
('PPI-206','PPI','Number of projects adopted by school/ community/ government','TPL2.1.8.FASDA-IMP.2','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Impact','Selected facilitators sustain and scale their initiatives post-program through external partnerships and support','Number of project that receive fund from schools, communities, or government to replicate or continue their implementation after the project period','Program Evaluation Survey',null),
('PPI-207','PPI','Total post-program funding secured (in IDR)','TPL2.1.8.FASDA-IMP.3','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Impact','Selected facilitators sustain and scale their initiatives post-program through external partnerships and support','Total amount of non-TF funding secured to support project continuation or replication after completion of the Fasda Perubahan program cycle','Program Evaluation Survey',null),
('PPI-208','PPI','Percentage of facilitators reporting application of at least one shared practice in their classroom','TPL2.1.8.FASDA-OC.1','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Outcome','Facilitators apply shared literacy and numeracy teaching practices in their classrooms','Numerator: Total of facilitators who report implementing at least one literacy or numeracy teaching practice shared in the community sessions in their classroom
Denumerator: Total Fasda who attend quarterly sharing session','Self Survey',null),
('PPI-209','PPI','Percentage of facilitators showing increased practice in project management, measurement, stakeholder collaboration','TPL2.1.8.FASDA-OC.2','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Outcome','Selected facilitators demonstrate increased practice in implementing and measuring innovation projects, building collaboration','Numerator: Total of Fasda whose post-test score is higher than their pre-test score on project management, measurement, and collaboration topics','Observation Survey',null),
('PPI-210','PPI','Percentage of literacy and numeracy innovation project fully implemented','TPL2.1.8.FASDA-OC.3','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Outcome','Selected facilitators demonstrate increased practice in implementing and measuring innovation projects, building collaboration','Numerator: Percentage of approved projects that complete all main activities as stated in the proposal

Denumerator: Total all approved projects','Project Tracker',null),
('PPI-211','PPI','Percentage of projects receive external support from school/community/government during project implementation period','TPL2.1.8.FASDA-OC.4','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Outcome','Selected facilitators demonstrate increased practice in implementing and measuring innovation projects, building collaboration','Number of project that receive fund or in-kind contribution from schools, communities, or government to replicate or continue their implementation after the project period',null,null),
('PPI-212','PPI','Total external support secured during the project implementation period (in IDR)','TPL2.1.8.FASDA-OC.5','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Outcome','Selected facilitators demonstrate increased practice in implementing and measuring innovation projects, building collaboration','Total non-TF support in form of in-kind or monetary',null,null),
('PPI-213','PPI','Percentage of facilitators demonstrate increased knowledge in developing literacy and numeracy innovation','TPL2.1.8.FASDA-IMO.1','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Intermediate Outcome','Facilitators demonstrate increased knowledge in developing literacy and numeracy innovation','Numerator: Total of Fasda whose post-test score is higher than their pre-test score on literacy and numeracy innovation topics.
Denumerator: Total Fasda who attend webinars','Pre & Post Test',null),
('PPI-214','PPI','Percentage of facilitators demonstrate increased knowledge in project management, measurement, stakeholder collaboration','TPL2.1.8.FASDA-IMO.2','Percent','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Intermediate Outcome','Selected facilitators demonstrate increased knowledge in implementing and measuring innovation projects, building collaboration','Percentage of Fasda whose post-test score is higher than their pre-test score on project management, measurement, and collaboration topics','Pre & Post Test',null),
('PPI-215','PPI','Number of collaboration plan created (incl. stakeholder mapping)','TPL2.1.8.FASDA-IMO.3','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Intermediate Outcome','Selected facilitators demonstrate increased knowledge in implementing and measuring innovation projects, building collaboration','Total number of collaboration plan documents submitted by participants after completing the stakeholder collaboration training','Submission form',null),
('PPI-216','PPI','Number of facilitators attend quarterly sharing session on literacy numeracy teaching good practices','TPL2.1.8.FASDA-O.1','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Output','Facilitators attend webinars','Total number of Fasda who attend at least one webinar session on developing literacy and numeracy innovation (headcount)','Attendance list',null),
('PPI-217','PPI','Number of facilitators attend quarterly sharing session on literacy numeracy teaching good practices','TPL2.1.8.FASDA-O.2','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Output','Facilitators attend quarterly sharing session','Total number of Fasda who attend at least one webinar session on developing literacy and numeracy innovation (headcount)','Attendance list',null),
('PPI-218','PPI','Number of proposals accepted','TPL2.1.8.FASDA-O.3','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Output','Facilitators submit project proposals','Total number of project proposals approved by Program Head based on the selection criteria','Memo of selection result',null),
('PPI-219','PPI','Number of facilitators receive grants','TPL2.1.8.FASDA-O.4','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Output','Facilitators submit project proposals','Total number of facilitators whose project proposals are approved through the formal selection process','Memo of selection result',null),
('PPI-220','PPI','Number of facilitators attend in training (project management, measurement, stakeholder collaboration, followed-up training)','TPL2.1.8.FASDA-O.5','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Output','Selected facilitators are participated in training (Camp Grantee)','Total number of Fasda who attend all of training session on project management, measurement, stakeholder collaboration, Followed-up training (headcount)','Attendance list',null),
('PPI-221','PPI','Number of facilitators attend in coaching','TPL2.1.8.FASDA-O.6','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Output','Selected facilitators are given','Total number of Fasda who attend all of coaching session (headcount)','Attendance list',null),
('PPI-222','PPI','Number of webinar session conducted','TPL2.1.8.FASDA-O.7','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Output','Webinars on innovation in literacy and numeracy','Total number of webinar sessions delivered for Fasda from 29 districts','Program Tracker',null),
('PPI-223','PPI','Number of quarterly sharing sesssion conducted','TPL2.1.8.FASDA-O.8','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Output','Quarterly sharing session on literacy numeracy teaching good practices','Total number of sharing session initiatives delivered for Fasda from 29 districts','Community Tracker',null),
('PPI-224','PPI','Number of proposal submitted','TPL2.1.8.FASDA-O.9','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Output','Project proposals submission','Total number of proposals submitted through the submission form, segregated by district and province','Submission Form.',null),
('PPI-225','PPI','Number of facilitators submit the proposals','TPL2.1.8.FASDA-O.10','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Output','Project proposals submission','Total number of Fasda from 13 eligible districts who submit proposals through the submission form','Submission Form.',null),
('PPI-226','PPI','Number of training session conducted','TPL2.1.8.FASDA-O.11','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Output','Training (Camp Grantee) on project management, measurement, and collaboration','Total number of training sessions (Camp Grantee) conducted for selected Fasda grant recipients','Program Tracker',null),
('PPI-227','PPI','Number of coaching session conducted','TPL2.1.8.FASDA-O.12','Number','Annual',null,null,null,null,null,null,'Children achieve minimum competency in literacy and numeracy','TFL2','Basic Education (BE)','TPL2.1','Fasilitator Daerah (Fasda)','TPL2.1.8','Output','Coaching on project planning, implementation, and evaluation','Total number of coaching sessions provided to selected Fasda grant recipients','Program Tracker',null),
('PPI-228','PPI','Percentage of alumni who become future leaders','TPL3.1.1.TELADAN-IMP.1','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Impact','Purpose-driven and mission-driven future leaders with a sustainability mindset who create a positive impact in their communities.','Numerator: # of alumni (3 years Post-Graduation – cohort 2019 & 2020) who become future leaders with a definition of having: Career Excellence, Influence, Pay it Forward for TELADAN program
Denominator: total of alumni per cohort (3 years Post-Graduation – coh…','Tracer study, alumni case studies, stakeholder testimonials',null),
('PPI-229','PPI','Number of university policies, programs, or initiatives supporting sustainable leadership development','TPL3.1.1.TELADAN-IMP.2','Number','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Impact','Thriving soft skill development ecosystem in higher education','Total of university that have policies, programs, or initiatives to supporting sustainable leadership development','University policy documents, leadership program reports',null),
('PPI-230','PPI','Percentage of alumni applied leadership competencies','TPL3.1.1.TELADAN-OC.1','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Outcome','TELADAN alumni applied their leadership competencies to build sustainable careers','Numerator: # of alumni that demonstrated leadership competencies in their work
Denominator: total number of alumni in the relevant cohort.','Tracer study, alumni case studies, stakeholder testimonials',null),
('PPI-231','PPI','Number of universities that adopt leadership development practices','TPL3.1.1.TELADAN-OC.2','Number','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Outcome','Scaling through partnership and collaboration with universities','Total universities that replication of leadership soft skill development practices','Cooperation documents',null),
('PPI-232','PPI','Percentage of scholars completed the program','TPL3.1.1.TELADAN-IMO.1','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Intermediate Outcome','Scholars complete their TELADAN program','Numerator: # of scholars cohort 2022 who completed the program
Denominator: total of regular scholars cohort 2022','Academic report (IP), scholar survey',null),
('PPI-233','PPI','Percentage of scholars that have leadership competencies.','TPL3.1.1.TELADAN-IMO.2','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Intermediate Outcome','Scholars demonstrate improved of soft skills, competencies and leadership values','Numerator: # of scholars cohort 2022 that have average score ≥2.3 out of 4.00 (end-line) leadership competencies
Denominator: total of scholars cohort 2022','Report competency assessment',null),
('PPI-234','PPI','Percentage of scholars who secure employment within ≤ 6 months after graduation','TPL3.1.1.TELADAN-IMO.3','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Intermediate Outcome','TELADAN alumni employed ≤ 6 months after graduation','Numerator: # of scholars cohort 2022 who obtain full-time, part-time, or self-employment within ≤ 6 months after graduation
Denominator: total of scholars cohort 2022','Alumni report, testimonials, tracer study',null),
('PPI-235','PPI','Number of scholar recipients','TPL3.1.1.TELADAN-O.1','Number','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output','Scholars receive financial support such as tuition fees and living allowances','Total number of scholarship recipients (TELADAN regular)','Scholarship database',null),
('PPI-236','PPI','Percentage of need based scholar','TPL3.1.1.TELADAN-O.2','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output',null,'Numerator: # of scholars from low income family (world bank standard)
Denominator: total scholars','Registration database',null),
('PPI-237','PPI','Percentage of scholars participating in Lead Self learning','TPL3.1.1.TELADAN-O.3','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output','Scholars participate in Lead Self learning','Numerator: # of scholars cohort 2025 & 2026 who completed Lead Self training
Denominator: total of scholars cohort 2025 & 2026','Attendance list, training certificates',null),
('PPI-238','PPI','Percentage of scholars participating in Lead Others learning','TPL3.1.1.TELADAN-O.4','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output','Scholars participate in Lead Others learning','Numerator: # of scholars cohort 2024 who completed in Lead Other training
Denominator: total of scholars cohort 2024','Attendance list, training certificates',null),
('PPI-239','PPI','Percentage of scholars participating in Professional Preparation learning','TPL3.1.1.TELADAN-O.5','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output','Scholars participate in Professional Preparation learning','Numerator: # of scholars cohort 2023 who completed in Professional Preparation training
Denominator: total of scholars cohort 2023','Attendance list, training certificates',null),
('PPI-240','PPI','Number of scholars participating in Professional Preparation learning','TPL3.1.1.TELADAN-O.6','Number','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output','Scholars participate in Learning Enrichment','Total number of scholars participate in Global Experience & Sponsorship','Attendance list, training certificates',null),
('PPI-241','PPI','Percentage of scholars participating in TSG','TPL3.1.1.TELADAN-O.7','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output',null,'Numerator: # of scholars participate in TSG
Denominator: total scholars per cohort','Attendance lists, event documentation, activity report',null),
('PPI-242','PPI','Percentage of scholars participating in TSA','TPL3.1.1.TELADAN-O.8','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output',null,'Numerator: # of scholars participate in TSA activities
Denominator: total of scholars per cohort','Attendance lists, event documentation, activity report',null),
('PPI-243','PPI','Number of alumni participating in networking and mentoring initiatives','TPL3.1.1.TELADAN-O.9','Number','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output','Alumni engagement activities implemented (gatherings, mentoring sessions, online platforms)','Total number of alumni that participating in networking and mentoring initiatives','Attendance lists, event documentation, mentoring reports',null),
('PPI-244','PPI','Number of alumni contribute back','TPL3.1.1.TELADAN-O.10','Number','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output',null,'Total number of alumni (TELADAN & Fellowship) involved in LDS program','Scholar survey',null),
('PPI-245','PPI','Number of universities receiving technical assistance','TPL3.1.1.TELADAN-O.11','Number','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output','Support for universities to implementation soft skill program','Total number of universities receiving technical assistance with TELADAN','MoM',null),
('PPI-246','PPI','Number of student reached dissemination','TPL3.1.1.TELADAN-O.12','Number','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output','Dissemination of soft skill training to students','Total number of students that participate through replication or dissemination by partner or non-partner university','Attendance list, training certificates',null),
('PPI-247','PPI','Number of institution participating','TPL3.1.1.TELADAN-O.13','Number','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','TELADAN','TPL3.1.1','Output','Community of practice forum','Total number of institutions that involved in community of practice forum','Forum report',null),
('PPI-248','PPI','Percentage of Fellows leading the development sector','TPL3.1.2.FELLOWSHIP-OC.1','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','Tanoto Foundation Fellowship','TPL3.1.2','Outcome','Multiplier Effect: Fellows contribute to the community',null,'Tracer study report',null),
('PPI-249','PPI','Percentage of Fellows entering relevant career pathways','TPL3.1.2.FELLOWSHIP-IMO.1','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','Tanoto Foundation Fellowship','TPL3.1.2','Intermediate Outcome',null,null,'Tracer study report',null),
('PPI-250','PPI','Percentage of Fellows demonstrate development in competency skills','TPL3.1.2.FELLOWSHIP-IMO.2','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','Tanoto Foundation Fellowship','TPL3.1.2','Intermediate Outcome',null,null,'Psychometric assessment report',null),
('PPI-251','PPI','Number of Fellows','TPL3.1.2.FELLOWSHIP-O.1','Number','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','Tanoto Foundation Fellowship','TPL3.1.2','Output','Self-transformation: Fellows improve skills and values to lead development sectors',null,'Program record',null),
('PPI-252','PPI','Percentage of Fellows program completion','TPL3.1.2.FELLOWSHIP-O.2','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','Tanoto Foundation Fellowship','TPL3.1.2','Output',null,null,'Program record',null),
('PPI-253','PPI','Percentage of Fellows who get exposure to field experience','TPL3.1.2.FELLOWSHIP-O.3','Percent','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','Tanoto Foundation Fellowship','TPL3.1.2','Output',null,null,'Baseline/End-line, qualitative study',null),
('PPI-254','PPI','Average of number organization that fellows network with','TPL3.1.2.FELLOWSHIP-O.4','Number','Annual',null,null,null,null,null,null,'Leaders contribute to the development of the country','TFL3','Leadership Development and Scholarship (LDS)','TPL3.1','Tanoto Foundation Fellowship','TPL3.1.2','Output',null,null,'MoM',null),
('PPI-255','PPI','1. Percentage of national subnational governments that demonstrate awareness (public statement)

2. Percentage of national subnational governments that demonstrate awareness (RPJMD in 2025, Renstra OPD in 2026 - Isu Strategis)','TPL5.1.1.PES-IMO.1','Percent','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Intermediate Outcome','IO.1.1: Government awareness and prioritization of PES issue improve, and government increasingly recognizes TF''s program as relevant solutions to PES challenges.','Government awareness: PES is clearly identified as a priority in strategic documents or public statements. This refers to whether the government explicitly recognizes PES as an important issue in:

1. official planning documents (e.g. RPJMD (done in 2025), Ren…','RPJMD, Renstra OPD, SE / Surat Edaran (normatif), Pidato/statement resmi pimpinan, (opsional) Permen/Perda jika hanya bersifat normatif/arah…',null),
('PPI-256','PPI','Number of TA, policy dialogues, advocacy meetings, or workshops conducted with government stakeholders, disaggregated by: 1. issue-based advocacy, 2. programme-based advocacy
(including: RPJMD workshop, Renstra OPD/Renja OPD workkshop with stakeholders)','TPL5.1.1.PES-O.1','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.1.1: Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF PES programs, including'||chr(59)||' RAS, and…','Total number of formal events (meetings, workshops, forums) with a defined PES agenda involving at least one government stakeholder. Fokus: workshop, forum, policy dialogue, meeting. Participant disini bisa lebih ke operasional dan teknis, ataupun dan bisa pel…',null,null),
('PPI-257','PPI','Number goverment official involved in the policy dialogue, workshop. or advocacy meeting','TPL5.1.1.PES-O.2','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.1.1: Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF PES programs, including'||chr(59)||' RAS, and…','Fokus: workshop, forum, policy dialogue, meeting. Lebih teknis / operasional, multi-participant, tidak selalu decision-maker. Excluding high-level leadership engagements',null,null),
('PPI-258','PPI','Number of advocacy materials produced and disseminated for policy dialogue, workshop, or/and advocacy meetings (policy briefs, presentations, communication products)','TPL5.1.1.PES-O.3','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.1.2: Targeted visibility and advocacy campaigns are delivered to strengthen public awareness of FLN issues.','Total number of finalized PES advocacy materials that have been distributed (e.g., policy briefs, presentations, communication products)',null,null),
('PPI-259','PPI','Number of media reports related to PES published in the past 12 months','TPL5.1.1.PES-O.4','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.1.2: Targeted visibility and advocacy campaigns are delivered to strengthen public awareness of FLN issues.','Total number of media articles (print/online) that substantively discuss PES within the past 12 months. Media visibility contributes to increasing public attention and pressure, which may influence government awareness and prioritization of PES. It is includin…',null,null),
('PPI-260','PPI','Percentage of policy drafts that demonstrate the integration of specific PES approaches (e.g. parenting stimulation, service delivery model, etc.) disaggregated by: issue-based advocacy exposure, programme-based advocacy exposure

Percentage of provinces produce draft of RAD SDGs 2025-2030 on PES','TPL5.1.1.PES-IMO.2','Percent','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Intermediate Outcome','I.O. 1.2: Government technical capacity to design and plan PES programmes improves, enabling the integration of PES approaches into operational planning and programme design and RAD SDGs 2025–2030.','PES is translated into concrete programmes/activities with defined outputs or targets in operational plans (actionable planning, but not yet funded)

A province is considered to have integrated PES and PES if at least ONE of the following is present in the RAD…','Draft RKPD, Draft Renja OPD, Draft Perbup / Perwali / Pergub (pedoman teknis / juknis), Draft Permen (sebagai acuan teknis jika digunakan di…',null),
('PPI-261','PPI','Number of technical assistance engagements, disaggregated by: issue-based advocacy, TF''s programme-based advocacy','TPL5.1.1.PES-O.5','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF PES programs, including'||chr(59)||' RAS, and S…','Number of governments that:

Include PES in operational planning documents (e.g., RKPD, Renja, programme design), Integrate PES into RAD SDGs 2025–2030 (targets, indicators, or programme priorities)',null,null),
('PPI-262','PPI','Number of policy drafts developed through TA, disaggregated by: issue-based advocacy, TF''s programme-based advocacy','TPL5.1.1.PES-O.6','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF PES programs, including'||chr(59)||' RAS, and S…',null,null,null),
('PPI-263','PPI','Number of policy recommendations submitted to government','TPL5.1.1.PES-O.7','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF PES programs, including'||chr(59)||' RAS, and S…','After the policy draft completed, it will be submitted to the BAPPEDA for review?',null,null),
('PPI-264','PPI','Number of government representatives participating in TA provided by TF on policy drafting','TPL5.1.1.PES-O.8','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF PES programs, including'||chr(59)||' RAS, and S…','Total number of unique government participants involved in TA activities',null,null),
('PPI-265','PPI','Number of provinces receiving technical assistance for RAD SDGs alignment (RAN-RAD) [GCB]','TPL5.1.1.PES-O.9','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF PES programs, including'||chr(59)||' RAS, and S…','Total number of provinces supported through TA to align RAD SDGs with PES priorities',null,null),
('PPI-266','PPI','Number of capacity strengthening activities conducted for RAD SDGs development (training/workshops/consultations) [GCB]','TPL5.1.1.PES-O.10','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF PES programs, including'||chr(59)||' RAS, and S…','Total number of training/workshops/consultations conducted to strengthen provincial capacity for RAD SDGs development related to PES',null,null),
('PPI-267','PPI','Number government official involved in the TA for RAD SDGs alignment','TPL5.1.1.PES-O.11','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF PES programs, including'||chr(59)||' RAS, and S…','Total number of government official involved in the TA for RAD SDGs alignment',null,null),
('PPI-268','PPI','Percentage of governments that allocate budget for PES programmes in official budget documents (APBD/DPA)','TPL5.1.1.PES-IMO.3','Percent','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Intermediate Outcome','I.O. 1.3: Governments adopt PES approaches into policies, programmes, and budgeting processes, demonstrating commitment through resource allocation and formal decision-making.','DPA
APBD
RKA OPD',null,null),
('PPI-269','PPI','Percentage of governments implementing PES programmes funded through public budgets

Percentage of governments that expand PES programme coverage beyond initial pilot areas','TPL5.1.1.PES-IMO.4','Percent','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Intermediate Outcome','I.O. 1.3: Governments adopt PES approaches into policies, programmes, and budgeting processes, demonstrating commitment through resource allocation and formal decision-making.','This is will be synced to the replication worksheet indicators',null,null),
('PPI-270','PPI','Number of budget advocacy engagements conducted to support PES integration into government budgeting processes (e.g. RKPD, KUA-PPAS, DPA)','TPL5.1.1.PES-O.12','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.3.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF PES programs, including'||chr(59)||' RAS, and S…',null,null,null),
('PPI-271','PPI','Number of technical assistance engagements provided to government for integrating PES into planning and budgeting documents','TPL5.1.1.PES-O.13','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.3.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF PES programs, including'||chr(59)||' RAS, and S…','after TA we produced this document',null,null),
('PPI-272','PPI','Number of engagements with government decision-makers (e.g. Bappeda, Dinas, leadership) to support PES programme funding and implementation','TPL5.1.1.PES-O.14','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.3.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF PES programs, including'||chr(59)||' RAS, and S…','Total number of government institutions receiving support to align PES programmes with formal budgeting processes',null,null),
('PPI-273','PPI','Number of policy inputs or recommendations generated through the ECED Council that are referenced or used in government policy, planning, or budgeting processes','TPL5.1.1.PES-IMO.5','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Intermediate Outcome','I.O 1.4: The ECED Council and collaborative ecosystem function
effectively to strengthen coordination, generate evidence,
and contribute to PES policy, planning, and budgeting
processes.','Functioned well --> should have the indicator on this, and whats the operational definition',null,null),
('PPI-274','PPI','Number of formal policy engagements (e.g. dialogues, consultations) involving ECED Council that contribute to PES policy, planning, or budgeting processes','TPL5.1.1.PES-IMO.6','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Intermediate Outcome','I.O 1.4: The ECED Council and collaborative ecosystem function
effectively to strengthen coordination, generate evidence,
and contribute to PES policy, planning, and budgeting
processes.',null,null,null),
('PPI-275','PPI','Percentage of PES-related policy or planning processes (e.g. RPJMD, RKPD) that involve inputs from ECED Council or collaborative platforms','TPL5.1.1.PES-IMO.7','Percent','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Intermediate Outcome','I.O 1.4: The ECED Council and collaborative ecosystem function
effectively to strengthen coordination, generate evidence,
and contribute to PES policy, planning, and budgeting
processes.',null,null,null),
('PPI-276','PPI','Number of joint advocacy actions conducted by ECED Council that lead to follow-up actions by government stakeholders','TPL5.1.1.PES-IMO.8','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Intermediate Outcome','I.O 1.4: The ECED Council and collaborative ecosystem function
effectively to strengthen coordination, generate evidence,
and contribute to PES policy, planning, and budgeting
processes.',null,null,null),
('PPI-277','PPI','Number of evidence products and policy briefs on PES developed through ECED Council','TPL5.1.1.PES-O.15','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.4.1: Strategic support, convening, and technical inputs are provided through the ECED Council and collaborative platforms to strengthen coordination, evidence generation, and joint advocacy for PES policy, planning, and budgeting.','ECED council established in the output level, functioned bisa di IO.',null,null),
('PPI-278','PPI','Number of ECED Council or collaborative platform engagements conducted with defined PES advocacy agenda','TPL5.1.1.PES-O.16','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.4.1: Strategic support, convening, and technical inputs are provided through the ECED Council and collaborative platforms to strengthen coordination, evidence generation, and joint advocacy for PES policy, planning, and budgeting.',null,null,null),
('PPI-279','PPI','Number of joint advocacy actions conducted through ECED Council (e.g. policy dialogues, campaigns, consultations)','TPL5.1.1.PES-O.17','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.4.1: Strategic support, convening, and technical inputs are provided through the ECED Council and collaborative platforms to strengthen coordination, evidence generation, and joint advocacy for PES policy, planning, and budgeting.',null,null,null),
('PPI-280','PPI','Number of stakeholders (government, academia, CSOs) engaged through ECED Council and collaborative platforms','TPL5.1.1.PES-O.18','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.4.1: Strategic support, convening, and technical inputs are provided through the ECED Council and collaborative platforms to strengthen coordination, evidence generation, and joint advocacy for PES policy, planning, and budgeting.',null,null,null),
('PPI-281','PPI','Number of high-level convenings facilitated through ECED Council involving government decision-makers on PES issues','TPL5.1.1.PES-O.19','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 1 - Parenting Early Stimulation (PES)','TPL5.1.1','Output','O.1.4.1: Strategic support, convening, and technical inputs are provided through the ECED Council and collaborative platforms to strengthen coordination, evidence generation, and joint advocacy for PES policy, planning, and budgeting.',null,null,null),
('PPI-282','PPI','Percentage of national subnational governments that demonstrate awareness (public statement)

Percentage of national subnational governments that demonstrate awareness (RPJMD in 2025, Renstra OPD in 2026 - Isu Strategis)','TPL5.1.2.FLN-IMO.1','Percent','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Intermediate Outcome','IO.1.1: Government awareness and prioritization of FLN issue improve, and government increasingly recognizes TF''s program as relevant solutions to FLN challenges.','Government awareness: FLN is clearly identified as a priority in strategic documents or public statements. This refers to whether the government explicitly recognizes literacy and numeracy (FLN) as an important issue in:

1. official planning documents (e.g. R…','RPJMD, Renstra OPD, SE / Surat Edaran (normatif), Pidato/statement resmi pimpinan, (opsional) Permen/Perda jika hanya bersifat normatif/arah…',null),
('PPI-283','PPI','Number of TA, policy dialogues, advocacy meetings, or workshops conducted with government stakeholders, disaggregated by: 1. issue-based advocacy, 2. programme-based advocacy
(including: RPJMD workshop, Renstra OPD/Renja OPD workkshop with stakeholders)','TPL5.1.2.FLN-O.1','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.1.1: Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF FLN programs, including'||chr(59)||' RAS, and…','Total number of formal events (meetings, workshops, forums) with a defined FLN agenda involving at least one government stakeholder. Fokus: workshop, forum, policy dialogue, meeting. Participant disini bisa lebih ke operasional dan teknis, ataupun dan bisa pel…',null,null),
('PPI-284','PPI','Number goverment official involved in the policy dialogue, workshop. or advocacy meeting','TPL5.1.2.FLN-O.2','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.1.1: Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF FLN programs, including'||chr(59)||' RAS, and…','Fokus: workshop, forum, policy dialogue, meeting. Lebih teknis / operasional, multi-participant, tidak selalu decision-maker. Excluding high-level leadership engagements',null,null),
('PPI-285','PPI','Number of advocacy materials produced and disseminated for policy dialogue, workshop, or/and advocacy meetings (policy briefs, presentations, communication products)','TPL5.1.2.FLN-O.3','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.1.2: Targeted visibility and advocacy campaigns are delivered to strengthen public awareness of FLN issues.','Total number of finalized FLN advocacy materials that have been distributed (e.g., policy briefs, presentations, communication products)',null,null),
('PPI-286','PPI','Number of media reports related to FLN published in the past 12 months','TPL5.1.2.FLN-O.4','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.1.2: Targeted visibility and advocacy campaigns are delivered to strengthen public awareness of FLN issues.','Total number of media articles (print/online) that substantively discuss FLN within the past 12 months. Media visibility contributes to increasing public attention and pressure, which may influence government awareness and prioritization of FLN. It is includin…',null,null),
('PPI-287','PPI','Percentage of policy drafts that demonstrate the integration of specific FLN approaches (e.g. parenting stimulation, service delivery model, etc.) disaggregated by: issue-based advocacy exposure, programme-based advocacy exposure

Percentage of provinces produce draft of RAD SDGs 2025-2030 on FLN','TPL5.1.2.FLN-IMO.2','Percent','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Intermediate Outcome','I.O. 1.2: Government technical capacity to design and plan FLN programmes improves, enabling the integration of FLN approaches into operational planning and programme design and RAD SDGs 2025–2030.','FLN is translated into concrete programmes/activities with defined outputs or targets in operational plans (actionable planning, but not yet funded)

A province is considered to have integrated FLN and FLN if at least ONE of the following is present in the RAD…','Draft RKPD, Draft Renja OPD, Draft Perbup / Perwali / Pergub (pedoman teknis / juknis), Draft Permen (sebagai acuan teknis jika digunakan di…',null),
('PPI-288','PPI','Number of technical assistance engagements, disaggregated by: issue-based advocacy, TF''s programme-based advocacy','TPL5.1.2.FLN-O.5','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF FLN programs, including'||chr(59)||' RAS, and S…','Number of governments that:

Include FLN in operational planning documents (e.g., RKPD, Renja, programme design), Integrate FLN into RAD SDGs 2025–2030 (targets, indicators, or programme priorities)',null,null),
('PPI-289','PPI','Number of policy drafts developed through TA, disaggregated by: issue-based advocacy, TF''s programme-based advocacy','TPL5.1.2.FLN-O.6','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF FLN programs, including'||chr(59)||' RAS, and S…',null,null,null),
('PPI-290','PPI','Number of policy recommendations submitted to government','TPL5.1.2.FLN-O.7','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF FLN programs, including'||chr(59)||' RAS, and S…','After the policy draft completed, it will be submitted to the BAPPEDA for review?',null,null),
('PPI-291','PPI','Number of government representatives participating in TA provided by TF on policy drafting','TPL5.1.2.FLN-O.8','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF FLN programs, including'||chr(59)||' RAS, and S…','Total number of unique government participants involved in TA activities',null,null),
('PPI-292','PPI','Number of provinces receiving technical assistance for RAD SDGs alignment (RAN-RAD) [GCB]','TPL5.1.2.FLN-O.9','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF FLN programs, including'||chr(59)||' RAS, and S…','Total number of provinces supported through TA to align RAD SDGs with FLN priorities',null,null),
('PPI-293','PPI','Number of capacity strengthening activities conducted for RAD SDGs development (training/workshops/consultations) [GCB]','TPL5.1.2.FLN-O.10','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF FLN programs, including'||chr(59)||' RAS, and S…','Total number of training/workshops/consultations conducted to strengthen provincial capacity for RAD SDGs development related to FLN',null,null),
('PPI-294','PPI','Number government official involved in the TA for RAD SDGs alignment','TPL5.1.2.FLN-O.11','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.2.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF FLN programs, including'||chr(59)||' RAS, and S…','Total number of government official involved in the TA for RAD SDGs alignment',null,null),
('PPI-295','PPI','Number of advocacy materials produced and disseminated for policy dialogue, workshop, or/and advocacy meetings (policy briefs, presentations, communication products)','TPL5.1.2.FLN-O.12','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.1.2: Targeted visibility and advocacy campaigns are delivered to strengthen public awareness of FLN issues.',null,null,null),
('PPI-296','PPI','Percentage of governments that allocate budget for FLN programmes in official budget documents (APBD/DPA)','TPL5.1.2.FLN-IMO.3','Percent','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Intermediate Outcome','I.O. 1.3: Governments adopt FLN approaches into policies, programmes, and budgeting processes, demonstrating commitment through resource allocation and formal decision-making.','DPA
APBD
RKA OPD',null,null),
('PPI-297','PPI','Percentage of governments implementing FLN programmes funded through public budgets

Percentage of governments that expand FLN programme coverage beyond initial pilot areas','TPL5.1.2.FLN-IMO.4','Percent','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Intermediate Outcome','I.O. 1.3: Governments adopt FLN approaches into policies, programmes, and budgeting processes, demonstrating commitment through resource allocation and formal decision-making.','This is will be synced to the replication worksheet indicators',null,null),
('PPI-298','PPI','Number of budget advocacy engagements conducted to support FLN integration into government budgeting processes (e.g. RKPD, KUA-PPAS, DPA)','TPL5.1.2.FLN-O.13','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.3.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF FLN programs, including'||chr(59)||' RAS, and S…',null,null,null),
('PPI-299','PPI','Number of technical assistance engagements provided to government for integrating FLN into planning and budgeting documents','TPL5.1.2.FLN-O.14','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.3.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF FLN programs, including'||chr(59)||' RAS, and S…','after TA we produced this document',null,null),
('PPI-300','PPI','Number of engagements with government decision-makers (e.g. Bappeda, Dinas, leadership) to support FLN programme funding and implementation','TPL5.1.2.FLN-O.15','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.3.1 Strategic technical assistance and policy inputs provided at national and subnational levels to strengthen education systems and inform planning, regulatory development, and budgeting for the scale-up of TF FLN programs, including'||chr(59)||' RAS, and S…','Total number of government institutions receiving support to align FLN programmes with formal budgeting processes',null,null),
('PPI-301','PPI','Number of advocacy materials produced and disseminated for policy dialogue, workshop, or/and advocacy meetings (policy briefs, presentations, communication products)','TPL5.1.2.FLN-O.16','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.1.2: Targeted visibility and advocacy campaigns are delivered to strengthen public awareness of FLN issues.',null,null,null),
('PPI-302','PPI','Number of policy recomendation produced','TPL5.1.2.FLN-IMO.5','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Intermediate Outcome','I.O. 1.4: A strengthened coalition and advocacy ecosystem effectively supports and influences government policy adoption and scaling of FLN initiatives.','Jumlah anggota koalisi yang berkontribusi dalam penyusunan rekomendasi kebijakan',null,null),
('PPI-303','PPI','Number of policy recommendation submitted in government policy event (e.g., musrenbang, uji publik, etc.,)','TPL5.1.2.FLN-IMO.6','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Intermediate Outcome','I.O. 1.4: A strengthened coalition and advocacy ecosystem effectively supports and influences government policy adoption and scaling of FLN initiatives.','Total number of advocacy actions or initiatives that are: Jointly conducted by coalition members,
What do we expect in this meeting: Explicitly aimed at influencing FLN-related policy (national or subnational), AND the policy is Implemented (not just planned)',null,null),
('PPI-304','PPI','Number of coalition forums or coordination meetings conducted','TPL5.1.2.FLN-O.17','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.4.1: Coalition coordination platforms are established and utilized to align stakeholders on FLN advocacy efforts.','Total number of formal coordination platforms/events conducted to align coalition members on FLN advocacy',null,null),
('PPI-305','PPI','Number of coalition members participating in meetings/activities','TPL5.1.2.FLN-O.18','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.4.2: Coalition members actively participate in coordinated meetings and joint advocacy activities.','Total number of unique coalition member organizations participating in coalition activities within a reporting period',null,null),
('PPI-306','PPI','Number of joint advocacy initiatives implemented','TPL5.1.2.FLN-O.19','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.4.3: Joint advocacy initiatives are implemented collaboratively by coalition members to influence FLN policy.','Total number of advocacy initiatives that: 1. Are co-designed and co-implemented, 2. Target FLN policy influence, 3. Have been executed (at least one advocacy output delivered)? discuss this with PA',null,null),
('PPI-307','PPI','Number of joint communication or advocacy products developed','TPL5.1.2.FLN-O.20','Number','Annual',null,null,null,null,null,null,'Ecosystems that support human capital development*','TFL5','Policy and Advocacy (PA)','TPL5.1','Goal 2 - Foundational Literacy and Numeracy (FLN)','TPL5.1.2','Output','O.1.4.4: Communication and advocacy products are developed collaboratively to strengthen the FLN agenda.','Total number of communication or advocacy products that are: 1. Co-developed, 2. Focused on FLN policy or advocacy agenda, 3. Finalized and disseminated',null,null)
on conflict (id) do update set
  type=excluded.type, name=excluded.name, code=excluded.code, unit=excluded.unit,
  calc=excluded.calc, t2030=excluded.t2030, strategy_map=excluded.strategy_map,
  outcome=excluded.outcome, accountability=excluded.accountability, program=excluded.program,
  details=excluded.details, toc_foundation=excluded.toc_foundation,
  toc_foundation_code=excluded.toc_foundation_code, portfolio=excluded.portfolio,
  portfolio_code=excluded.portfolio_code, project=excluded.project,
  project_code=excluded.project_code, level=excluded.level,
  result_statement=excluded.result_statement, definition=excluded.definition,
  mov=excluded.mov, period=excluded.period;

select type, count(*) as indikator from public.indicators group by type order by type;
